folio-org/mod-source-record-manager

pom.xml, src/main/java/org/folio/dao/JobExecutionDao.java, src/main/java/org/folio/dao/JobExecutionDaoImpl.java, src/main/java/org/folio/rest/impl/ChangeManagerImpl.java, src/main/java/org/folio/services/JobExecutionService.java, src/main/java/org/folio/services/JobExecutionServiceImpl.java, src/main/java/org/folio/util/OkapiConnectionParams.java, src/main/java/org/folio/util/RestUtil.java, src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
- REST method receives InitJobExecutionsRqDto with files,
- Service method does parentJobExecutionId generation,
- Service method prepares a necessary amount of JobExecution entities,
- Service method prepares a necessary amount Snapshot json entities,
- Service method does save prepared JobExecution entities using DAO,
- Service method calls mod-source-record-storage to save prepared Snapshots,
- Service method completes future and returns InitJobExecutionsRsDto with parentJobExecutionId and prepared JobExecution entities,
- REST method returns response containing InitJobExecutionsRsDto
=> Modsourman 9 Initializing job executions

mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionService.java, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/converters/JobExecutionToDtoConverter.java, mod-source-record-manager-server/src/main/java/org/folio/services/converters/JobExecutionToLogDtoConverter.java, mod-source-record-manager-server/src/main/java/org/folio/services/parsers/RecordFormat.java, mod-source-record-manager-server/src/test/java/org/folio/dao/JobExecutionDaoImplUnitTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderLogAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/converters/JobExecutionToDtoConverterUnitTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/converters/JobExecutionToLogDtoConverterUnitTest.java, mod-source-record-manager-server/src/test/resources/org/folio/services/converters/jobExecutionCollectionMultipleTest.sample, mod-source-record-manager-server/src/test/resources/org/folio/services/converters/jobExecutionCollectionSingleTest.sample, ramls/change-manager.raml
* Add jobExecution dependency on DataType (MARC, BIBFRAME, EDIFACT, etc.)
* Implement the stub getRecordFormatByJobExecution method in ChangeEngineService based on the dataType associated with JobExecution
* Remove jobProfile schema from mod-source-record-manager schemas
* Change /change-manager/jobExecutions/id/jobProfile endpoint implementation that assigns JobProfile to JobExecution
* Update calls to the mentioned above endpoint from mod-data-import module
=> Modsourman 67 Remove JobProfile from the module 

mod-source-record-manager-server/src/main/resources/rules.json
Moved mapping rules for 'notes' field into "entity" framing (instead of raw fields list) 
to run mapping in much optimized manner and do not spawn redundant objects.
=> MODSOURMAN-153 - Optimize record-to-instance mapping

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParameters.java, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParametersBuilder.java, mod-source-record-manager-server/src/main/resources/rules.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java, mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json, ramls/change-manager.raml, ramls/settings/instanceformat.json, ramls/settings/instanceformats.json
- In the Create/Edit screen, this is one value (Format) with 2 terms hyphenated together in the dropdown list (Category and Term)
- In the View details screen, there are 4 values: Category, Term, Code, and Source
- Valid values are listed in the tenant’s Settings/Inventory/Format
- Comes from the 337 and 338 fields of the MARC record
- Mapping: 
337 $a: Format Category
338 $a: Format Term
338 $b: Format Code
338 $2: Format Source
- Note: MARC 337/338 fields are repeatable. Instance Format is also repeatable. If multiple 3372/3382, pair the first 337$a with the first 338 $a$b$2. Pair the second 337$a with the second 338 $a$b$2. Etc.
=> MODSOURMAN-172 Added instance-format settings loading for mapping

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java, mod-source-record-manager-server/src/main/resources/rules.json, mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
Identifier: GPO and Cancelled GPO number (rows 14, 15)
Review the subfields carefully to determine GPO Identifier Type
074 $a = [Valid] GPO item number
074 $z = Cancelled GPO item number
Each of the above subfields should be in a separate Instance GPO number field, even if they are in the same MARC 074 field
Examples
074 \\$a1002-A
074 \\$a1002-B (MF)
Become
GPO item number 1002-A
GPO item number 1002-B (MF)
074 \\$a1022-A$z1012-A
Become
GPO item number 1022-A
Cancelled GPO item number 1012-A
=> MODSOURMAN-194 Added mapping for GPO and Cancelled GPO number identifier types

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java, mod-source-record-manager-server/src/main/resources/rules.json, mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java, mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json
For most 035 $a, identifier type should be System control number
BUT: if the 035 $a begins with
(OCoLC)
ocm
ocn
on
Then assign Identifier type OCLC instead
019 $a and 035 $z should always be assigned identifier type Cancelled system control number
Each number (subfield a or z) always goes in a separate identifier field in the Instance, even if they are in the same MARC 035 field
=> MODSOURMAN-193 Added mapping for System control number vs. OCLC number

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODSOURMAN-234 FOLIO-2358 manage container memory

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/AdditionalFieldsUtil.java, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldServiceImpl.java
1. The 035 field should indicators 1 and 2 of [blank] (currently no JSON for indicators in the screenshot where 035 looks like a fixed field)
2. The contents of the former 001 field should be in subfield a of the 035 field (currently no subfield)
3. If there are existing 035 fields, the newly-created 035 should be a completely new 035 (since 035 is a repeatable field)
4. If the newly-created 035 matches an existing 035 exactly, then do not add that new 035 field.
5. If possible, put the newly-created 035 fields in numeric order within the 0XX fields (but DO NOT resequence the entire MARC record into numeric order)
6. Fix stub data and recalculate leader
=> Moddicore 43: Fix formatting of 035 field constructed from incoming 001

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerParsedRecordsAPITest.java, ramls/change-manager.raml
The update of the SRS MARC Record and the corresponding inventory Instance happens using pub-sub approach. Change Manager publishes an event upon receiving the request, and all the processing of MARC and Instance happens in other modules. Hence, 202 http response status (ACCEPTED) is more appropriate than 204.
=> MODSOURMAN-321 Return 202 when request for update of parsed record is received

.rancher-pipeline.yml, NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/resources/log4j2.properties, mod-source-record-manager-server/src/main/resources/vertx-default-jul-logging.properties
1. New config file "vertx-default-jul-logging" for overriding vertx-jul added with disabling(except ERROR log-level) CQL2PgJSON.
2. Disabling CQLWrapper to log4j2.properties added.
3. "-Djava.util.logging.config.file=vertx-default-jul-logging.properties" added for ModuleDescriptor.
4. "-Djava.util.logging.config.file=vertx-default-jul-logging.properties" to the .rancher-config-file.
5. NEWS updated.
=> MODSOURMAN-339: Disable CQL2PgJSON & CQLWrapper extra logging in mod-source-record-manager.

NEWS.md, RuleProcessorApi.md, mod-source-record-manager-server/src/main/resources/rules/rules.json, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
Add MARC-Instance default mappings for 880 fields.
It based on the rules below:
* Finds 880 field from the record. If exists, then retrieve first 3 digits from subfield '6'.
* If there is value from this list: 100, 110, 111, 245 - then field-value '880' will be changed on 700,710,711,246 respectively.
* Otherwise, '880' will be changed on the first 3-digits value.
1. rules.json updated with 880 field.
2. NEWS updated.
Other PR for this functionality: https://github.com/folio-org/data-import-processing-core/pull/114
More info: https://issues.folio.org/browse/MODDICORE-114
=> MOODDICORE-114: Add MARC-Instance default mappings for 880 fields .

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/rules.json, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
Update 5xx Notes mappings to indicate staff only for some notes.
Some 5xx note fields have indicators that correspond to staff only. Right now the default MARC-Instance mapping is only mapping based on the 5xx field value, not indicator values. The default rules need to be adjusted to take into account the Staff only checkbox as indicated below.
For the following notes fields:
* 541 Immediate source of acquisition note
* 542 Information related to copyright status note
* 561 Ownership and custodial history note
* 583 Action note
If the first indicator = 0, then mark the "Staff only" checkbox
If the first indicator = anything else, then DO NOT mark the "Staff only" checkbox
1. Rules for 541, 542, 561, 583 staffOnly added. "set_note_staff_only_via_indicator" function added. 
2. NEWS …
=> MODSOURMAN-377: Update 5xx Notes mappings to indicate staff only for some notes. 

descriptors/ModuleDescriptor-template.json, ramls/change-manager-handlers.raml, ramls/change-manager.raml, ramls/mapping-rules-provider.raml, ramls/metadata-provider.raml
* source-manager-event-handlers API version needs to be bumped after /change-manager/handlers/processing-result and /change-manager/handlers/created-inventory-instance endpoints were removed
* remove unnecessary interface dependencies on batch save APIs
* versions declared in the ModuleDescriptor should match versions in raml
=> Update interface versions

mod-source-record-manager-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/StoredRecordChunkConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredMarcChunksKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java
Resolves [MODSOURMAN-408](https://issues.folio.org/browse/MODSOURMAN-408)
Requires https://github.com/folio-org/data-import-raml-storage/pull/207
=> MODSOURMAN-408: Publish event about EDIFACT record creation

mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java
Different consumers from the same group can't get the same type of event from kafka.
Improving module name for groupId.
[MODSOURMAN-384](https://issues.folio.org/browse/MODSOURMAN-384)
=> Improving module name for receiving one type of event by different consumers.

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
*Overview:* 2 bugs: 1) Regardless of whether a new instance is being created or an existing instance is being updated, the data import profile used by Inventory Single Record Import is the "update" profile. 2) The update job gets stuck in Running and never finishes
Expected Results: 
First import: should create a new instance and new SRS MARC, using the Default create instance job profile
Second import: should update the existing instance and create a new SRS MARC, using the Default update instance job profile
=> MODDATAIMP-370

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
When records are posted directly to SRS via the API, they may not have sequence numbers. Thus, the log information is difficult to access. This story ensures that the log summary screen includes sequence numbers for the records that were posted via API.
* expanded logic of endpoint for posting records' chunks
* covered with test
[MODDATAIMP-384](https://issues.folio.org/browse/MODDATAIMP-384)
=> MODSOURMAN-422 - Add record sequence number for records posted direct via API

mod-source-record-manager-server/src/main/java/org/folio/config/ApplicationConfig.java, mod-source-record-manager-server/src/main/java/org/folio/services/DataImportPayloadContextBuilder.java, mod-source-record-manager-server/src/main/java/org/folio/services/DataImportPayloadContextBuilderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/DataImportPayloadContextBuilderImplTest.java
To support importing Marc Authority records, change the way how Data Import event payload is populated. Create a payload context depending on the type of Marc record. For Authority records the payload has to contain only the record mapped to "MARC_AUTHORITY" key. See [MODSOURMAN-411](https://issues.folio.org/browse/MODSOURMAN-411)
* introduce `DataImportPayloadContextBuilder `interface to encapsulate the logic of populating data import context.
* implement context population inside `DataImportPayloadContextBuilderImpl`. For authority records add the record into the context; for other type of records, including EDIFACT invoice and Marc Bib, add the record, mapping rules, mapping parameters, as it was before the change
* inside `DataImportPayloadContextBuilderImpl` use `MarcRecordAnalyzer` …
=> MODSOURMAN-411 Dynamicaly define the payload of Data Import events depending on MARC Record type (Bib, Authority, Holding)

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JournalRecordsColumns.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java, ramls/metadata-provider.raml
to provide data of the particular invoice line for Invoice JSON screen
* expanded get_job_log_entries() function to return invoiceLineJournalRecordId
* changed create_get_record_processing_log_function() function to retrieve data only for the certain invoice line
* covered with tests
[MODSOURMAN-420](https://issues.folio.org/browse/MODSOURMAN-420)
Requires: https://github.com/folio-org/data-import-raml-storage/pull/212
=> MODSOURMAN-420 - Expand endpoint for retrieving recordProcessingLogDto to support Invoice JSON screen

descriptors/ModuleDescriptor-template.json
Endpoint `PUT /change-manager/jobExecutions/{id}/jobProfile` is making request to `GET /data-import-profiles/jobProfiles/{id}` so it should have one more modulePermission: `converter-storage.jobprofile.get`
=> MODSOURMAN-429 Add permission to `/change-manager/jobExecutions/{id}/jobProfile`

NEWS.md, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunkConsumersVerticleTest.java
to fix the hang of the job when MARC record type can not be determined
* publish DI_ERROR event when record type can not be determined by value at LEADER/06
[MODDATAIMP-403](https://issues.folio.org/browse/MODDATAIMP-403)
Requires: https://github.com/folio-org/data-import-utils/pull/40
=> MODDATAIMP-403 - Some data import jobs stuck on folio-snapshot-load

NEWS.md, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/config/ApplicationConfig.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunkConsumersVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java
to expand exactly one delivery approach for chunks of saved records in srs
* KafkaInternalCache was used to check whether an event was already consumed by the handler
[MODSOURMAN-428](https://issues.folio.org/browse/MODSOURMAN-428)
=> MODSOURMAN-428 - Expand exactly one delivery approach for handler receiving stored records

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportJournalKafkaHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleTest.java
to expand exactly one delivery approach for chunks of saved records in srs
* KafkaInternalCache was used for event deduplication
* consumed event id is preceded with `DataImportJournalKafkaHandler` handler class name before placement to the cache to distinguish the same identifiers placed in the cache by other handlers (for instance by handler from mod-inventory)
[MODSOURMAN-430](https://issues.folio.org/browse/MODSOURMAN-430)
=> MODSOURMAN-430 - Expand exactly once delivery approach for data import log handler

NEWS.md, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/util/EventHandlingUtil.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportJournalKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportKafkaHandler.java
to facilitate tracing of processing of a particular record
* new correlationId is set before publishing event with particular record
* correlationId is logged from a kafka event header
[MODSOURMAN-437](https://issues.folio.org/browse/MODSOURMAN-437)
=> MODSOURMAN-437 - Add logging for event correlationId

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionsCache.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleTest.java
The Data Import landing page queries the back-end SRM for the job's status. The SQL query to poll is not performant and can use up to 10% of CPU for one user. 
Cache was added
=> MODSOURMAN-436 Slow Query Invoked on DI Home Page

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java
Apply MarcRecordAnalyzer to determine MARC related specific record type in ChangeEngineServiceImpl on record creation.
inject analyzer(marcRecordAnalyzer) for retrieving record type by leader
https://issues.folio.org/browse/MODSOURMAN-497
=> MODSOURMAN-497 Apply MarcRecordAnalyzer to determine MARC related specific type

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/progress/JobExecutionProgressServiceImpl.java
The purpose is to fix the deadlock that is caused by updating the "job_monitoring" and  "job_execution_progress" tables
See https://issues.folio.org/browse/MODSOURMAN-509 for more details.
The approach is to update "job_monitoring" and  "job_execution_progress" tables independently so that exceptions from updating "job_monitoring" will not affect updates for "job_execution_progress".
The approach is tested on the local machine,  now we need to verify it on reference envs using various import properties and marc files
=> MODSOURMAN-509 - Data import stopped process before finishing: deadlock for job_monitoring

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportJournalKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/EventTypeHandlerSelector.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/EventTypeHandlerSelectorTest.java
to adjust statuses on the summary page after updating an existing Instance and creating a new SRS MARC implicitly using single record imports for Overlays
* ensure title log when logging an event that record has been updated
* introduce events that notify that a record has been created/updated implicitly after updating an instance
[MODSOURMAN-508](https://issues.folio.org/browse/MODSOURMAN-508)
=> MODSOURMAN-508 - Log details for Inventory single record imports for Overlays - Part 2

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/QuickMarcEventProducerService.java, mod-source-record-manager-server/src/main/java/org/folio/services/QuickMarcEventProducerServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/util/EventHandlingUtil.java
https://issues.folio.org/browse/MODSOURMAN-517
Change quickMarc producers not to close after message sent. Currently, they are created each time the event send and then closed
Create shared producers and store them in map
Do not close producer after message sent
=> MODSOURMAN-517 - Change quickMarc producers not to close

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
When calculating ##TODAY## in a profile run at the end of the day, data import used the next day's date. Perhaps not using DST correctly. Observed on Cornell's tenant which is America/New York.
Created brand new mechanism:
1. Retrieve tenant configuration from "/configurations/entries" in srm. There will be a current timezone for the tenant. (By default, it is empty, so it'll proceeded with UTC-timezone). Put this into MappingParameters to the dataImportEventPayload.
2. In di-core while processing ##TODAY##-expression retrieve from dataImportEventPayload current timezone for the tenant, calculate current dateTime in UTC(default) and convert to the timezone for the tenant.
**This PR should be merged after this PR will be merged: https://github.com/folio-org/data-import-processing-core/pull/ …
=> MODDICORE-166: Near the day boundary data import calculates today incorrectly.

descriptors/ModuleDescriptor-template.json
Changed quickMarc update flow requires changes in SRM to support the new inventory-storage endpoint.
- add "inventory-storage.instances.preceding-succeeding-titles.collection.put" to module permissions for the *PUT /change-manager/parsedRecords/ {id}
endpoint*
- add "instance-preceding-succeeding-titles v0.2" interface to descriptor's requires section
[MODSOURMAN-538](https://issues.folio.org/browse/MODSOURMAN-538)
=> MODSOURMAN-538 Updated descriptor for PUT /change-manager/parsedRecords/{id}

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordService.java, mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerParsedRecordsAPITest.java, ramls/change-manager.raml
Update GET /change-manager/parsedRecords  to have externalId param instead instanceId. It will give quick-marc an ability to fetch records by its externalId from SRS.
instanceId parameter is replaced with externalId 
[MODSOURMAN-553](https://issues.folio.org/browse/MODSOURMAN-553)
[API Documentation](https://s3.amazonaws.com/foliodocs/api/mod-source-record-manager/change-manager.html#change_manager_parsedrecords_get)
=> MODSOURMAN-553 Update GET /change-manager/parsedRecords to have externalId param

descriptors/ModuleDescriptor-template.json
since mapping metadata (mapping rules and parameters) should be deleted from the data-import payload it is  necessary to provide permission for modules participating in data-import to retrieve mapping metadata in case, when data-import is  initiated with sourceType="ONLINE" (bypassing the mod-data-import)
[MODSOURCE-286](https://issues.folio.org/browse/MODSOURCE-286)
=> MODSOURCE-286 - Provided module permission for retrieving mapping metadata

mod-source-record-manager-server/src/main/java/org/folio/dao/MappingRuleDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/MappingRuleCache.java, mod-source-record-manager-server/src/main/java/org/folio/services/entity/MappingRuleCacheKey.java, mod-source-record-manager-server/src/test/java/org/folio/dao/MappingRuleDaoImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerParsedRecordsAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java
After introducing mapping rules for MARC_HOLDINGS a new logic was added for saving mapping rules for different MARC files. The implementation didn't take into account that there is no mapping rules for EDIFACT, and this step should be skipped for such records.
=> MODSOURMAN-560 Fix getting rules for records

mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java
During import marc holding by using data-import-flow, on the snapshot environment we receive error while data-import try to build journal record/instance.
- added entity type for marc holding during throw di_error
- removed checking on the marc holdings from payload
https://issues.folio.org/browse/MODSOURMAN-561
=> MODSOURMAN-561 Can`t map record into journal

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json
In scope of adding Cancelled system control number as resource identifier type:
-	Added mapping rules for 019$a and 035$z subfields;
https://issues.folio.org/browse/MODSOURMAN-563
=> MODSOURMAN-563 Add MARC-Instance field mapping for Cancelled system control number

descriptors/ModuleDescriptor-template.json
to fix definition for "GET /mapping-metadata/{jobExecutionId}" endpoint,
currently, we get 404 in response with the following message: 
> No suitable module found for path /mapping-metadata/8d679c03-4a86-42ca-a7eb-0e4593400d37 for tenant diku
=> MODDATAIMP-544 - Fixed endpoint definition for mapping metadata retrieving

mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
verify rule type on the creation during replace module into local vagrant
Fixed script by adding verification on the existing rele_type
https://issues.folio.org/browse/MODSOURMAN-564
=> MODSOURMAN-564 Error during replacement module in local vagrant

NEWS.md, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerParsedRecordsAPITest.java
In the scope of the Optimistic locking feature, mod-source-record-manager needs to pass along 'relatedRecordVersion' through the event chain. This story intended to add this field and update test(s).
updated raml storage to have the latest updates from the master branch
updated test with new property 'relatedRecordVersion'
=> MODSOURMAN-577 - Optimistic locking: mod-source-record-manager modifications

mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java
in the scope of https://issues.folio.org/browse/MODSOURMAN-581 needs to return two additional columns to form title for HOLDINGS records
* updated script to return two additional columns - source_record_entity_type and holdings_entity_hrid
* updated schemas from the master version
* updated the logic to return holdings title
=> MODSOURMAN-581 - Populate title for MARC Holdings

mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/exceptions/RecordsProcessingException.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/RawMarcChunkConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/StoredRecordChunkConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/StoredRecordChunksErrorHandler.java, mod-source-record-manager-server/src/main/resources/log4j2.properties, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunkConsumersVerticleTest.java
mod-source-record-manager should implement error's handler to send to Kafka DI_ERROR event if processing was with exception.
In handler's implementation need to make sure, that DI_ERROR thrown for particular record, not for all file taken to process.
This new error handler should be specified during creating of KafkaConsumerWrapper instance.
Adding error handler's for each processing service will help to resolve issue when progress-bar in UI got stuck, import should be 'Completed with errors' in case of failures.
Workflow for implemented error handlers:
=> MODSOURMAN-474. Implement ProcessRecordErrorHandler for Kafka Consumers

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionsCache.java
"View all" and "Load more" buttons in Data Import should load all logs but are not.
It seems like "limit" and "offset" params from the request are not concatenated to the query, which will be used in Cache. That's why queries with the difference limit and offset are the same as in the Cache. That's why in response there are the same results. 
This fix added "LIMIT and OFFSET" params to store them in the cache (create them unique).
JIRA: https://issues.folio.org/browse/MODSOURMAN-595
=> MODSPURMAN-595: "View all" and "Load more" buttons do not load all logs in Data Import

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
Cannot build journal record when entity is empty
Added additional entity validation for emptiness
[MODSOURMAN-594](https://issues.folio.org/browse/MODSOURMAN-594)
=> MODSOURMAN-594 Cannot build journal record when entity is empty

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java, mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
https://issues.folio.org/browse/MODSOURMAN-614
The purpose is to have an ability to map the note types from incoming marc record
- Update MappingParametersProvider
- Update ModuleDescriptor to add new permissions
- Update marc_authority_rules.json
- Update tests
=> MODSOURMAN-614 Authority: Add mapping rule for note types

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java
Prevent sending DI_ERROR event in srm when detected duplicate event
- Removed throwable's catcher-mapper in AbstractChunkProccessingService
- Defining UNIQUE CONSTRAINT VIOLATION using Postgres error code and throwable instance
https://issues.folio.org/browse/MODSOURMAN-598
=> MODSOURMAN-598 Properly handle DB failures during events processing

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
Fix handling DI_ERROR when 004 is invalid in MARC Holdings not to make import stuck
- add `recordId` header to kafka event
- cover case with unit-test
[MODSOURMAN-624](https://issues.folio.org/browse/MODSOURMAN-624)
=> MODSOURMAN-624 Failed to handle DI_ERROR when 004 is invalid in MARC Holdings

mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, pom.xml
Update dependencies:
* RMB from 33.0.2 to 33.2.0
* Vert.x from 4.1.0 to 4.2.1
* Jackson from 2.9.9 to 2.10.5
* folio-di-support from 1.1.0 to 1.4.1
* mod-source-record-storage-client from 5.2.0 to 5.2.5
* kafka-junit from 2.5.0 to 2.8.0
=> MODSOURMAN-628: RMB 33.2.0, Vert.x 4.1.2

NEWS.md, mod-source-record-manager-server/pom.xml, pom.xml
to fix  vulnerability that is present in log4j<= 2.14
* upgrade log4j version to 2.16.0
[MODSOURMAN-646](https://issues.folio.org/browse/MODSOURMAN-646)
=> MODSOURMAN-646 - Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, mod-source-record-manager-server/pom.xml, pom.xml
to fix  vulnerability that is present in log4j<= 2.14
* upgrade log4j version to 2.16.0
[MODSOURMAN-648](https://issues.folio.org/browse/MODSOURMAN-648)
=> MODSOURMAN-648 - Juniper R2 2021 - Log4j vulnerability verification and correction

mod-source-record-manager-server/pom.xml, pom.xml
Remove unused cql2pgjson:4.0.0.
Update Vert.x from 4.2.1 to 4.2.2.
Update JUnit from 4.13 to 4.13.2.
This fixes these vulnerabilities:
cql2pgjson: "MITM attack http maven repository" https://issues.folio.org/browse/RMB-823 https://maven.apache.org/docs/3.8.1/release-notes.html#cve-2021-26291
Vert.x/Netty: "HTTP request smuggling" https://nvd.nist.gov/vuln/detail/CVE-2021-43797
JUnit: "TemporaryFolder local information disclosure" https://nvd.nist.gov/vuln/detail/CVE-2020-15250
=> MODSOURMAN-651: cql2pgjson, Vertx 4.2.2, JUnit 4.13.2

mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json
MARC tag 010 $a and $z values may have leading and trailing whitespaces
Added trim to condition for 010 field
https://issues.folio.org/browse/MODSOURMAN-654
=> MODSOURMAN-654 Import MARC authority records > Trim leading and trailing whitespaces on MARC 010

mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java
To have an ability to Log Authority records that were updated/matched or not matched
Update JournalParams, and DataImportJournalConsumersVerticle
The matched and non-matched records are getting logged into Journal
The new code is covered by unit tests (JournalParamsTest)
https://issues.folio.org/browse/MODSOURMAN-653
=> MODSOURMAN-653 Authority update: Make Journal to log authorities

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
Fix sorting of edifact invoices in logs
- Added additionaly logic when we sort using source_record_order, now we replace this to other field - source_record_order_array
- Added new column(source_record_order_array) to function get_job_log_entries
- When we sort invoice, function use entity_hrid as int array. In other cases source_record_order as array with single element
https://issues.folio.org/browse/MODSOURMAN-625
=> MODSOURMAN-625 Invoice log detail sort by Record column in Data Import detail log not working properly

mod-source-record-manager-server/pom.xml
jackson-databind 2.10 has been closed since 2021-09-30, doesn't get any updates and therefore can no longer been used in critical production code: https://github.com/FasterXML/jackson/wiki/Jackson-Releases
Bumping the kafka-junit version from 2.8.0 to 3.0.0 bumps the jackson-databind version from 2.10.5.1 to 2.12.6. The version 2.12.* is still maintained and receives security patches.
=> MODSOURMAN-636 update kafka-junit and jackson dependencies

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/QuickMarcUpdateKafkaHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/QuickMarcUpdateKafkaHandlerTest.java
Kafka Cache is used in QuickMarcUpdateKafkaHandler in SRM. Just remove Kafka cache (consumer receiving QM_COMPLETED supports deduplication).
[MODSOURMAN-664](https://issues.folio.org/browse/MODSOURMAN-664)
=> MODSOURMAN-664 Remove Kafka cache from QuickMarc handlers

mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/services/EventProcessedServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportJournalKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/StoredRecordChunksErrorHandler.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/EventProcessedServiceTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportKafkaHandlerMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java
Prevent logging of full stack traces for duplicate event to not confuse that someting was wrong
**Example of such stack trace:**
10:01:36.749 [vert.x-worker-thread-0] ERROR KafkaConsumerWrapper [138548eqId] Error while processing a record - id: 81 subscriptionPattern: SubscriptionDefinition(eventType=DI_PARSED_RECORDS_CHUNK_SAVED, subscriptionPattern=FOLIO.Default.\w{1,}.DI_PARSED_RECORDS_CHUNK_SAVED) offset: 2 org.folio.dataimport.util.exception.ConflictException: Event with eventId=4013eb1c-83ce-4782-b6d7-bbda4a4323e3 for handlerId=4d39ced7-9b67-4bdc-b232-343dbb5b8cef is already processed. at org.folio.services.EventProcessedServiceImpl.lambda$collectData$0(EventProcessedServiceImpl.java:28) ~[mod-source-record-manager-server-fat.jar:?] at …
=> Improve logging for handling duplicate events to not write in logs full stack trace

mod-source-record-manager-server/pom.xml
Kafka clients 3.0.0 version contained an issue with running tests on Windows machine.
https://issues.apache.org/jira/browse/KAFKA-13391
Since 3.0.1 it was fixed so applying this new version in SRM
Increase version of kafka-clients
=> Update Kafka clients version to fix unit tests on Windows

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json
Incorrect mapping "020" marc field when fields repeated:
**=020  \\$a9780471622673$q(acid-free paper)$a0471725331$q(electronic bk.)**
_Expected result:_
ISBN : 9780471622673 (acid-free paper)
ISBN : 0471725331 (electronic bk.)
_Actual result:_
ISBN :  (acid-free paper) 0471725331 (electronic bk.)
ISBN :  9780471622673
- Added [entityPerRepeatedSubfield flag](https://github.com/folio-org/mod-source-record-manager/blob/master/RuleProcessorApi.md#new-object-per-repeated-sub-fields) to 020 field
- Replaced [applyRulesOnConcatedData flag](https://github.com/folio-org/mod-source-record-manager/blob/master/RuleProcessorApi.md#processing-rules-on-concatenated-data) to [subfieldsToConcat flag](https://github.com/folio-org/mod-source-record-manager/blob/master/RuleProcessorApi.md#required-sub-fields …
=> MODSOURMAN-675 Data Import handles repeated 020 $a:s in an unexpected manner when creating Instance Identifiers

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JournalRecordsColumns.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
Extend functionality for /metadata-provider/jobLogEntries endpoint to provide information about Instance even if no action was performed on Instance.
Added two new columns for journal_records table (instance_id and holdings_id) and implemented functionality to work with them.
[MODSOURMAN-676](https://issues.folio.org/browse/MODSOURMAN-676)
There are also known issue:
For the case, when we are going to only update ITEM entity with matching on ITEM's field, we will not get hotlink due to no information about INSTANCE entity (instanceId and holdingId are required to build hotlink for the ITEM entity).
=> MODSOURMAN-676 Provide Instance UUID for populating Inventory hotlinks for holdings/items

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java
The jsonb->id field was used for queries.
A separate "id" search field was used.
https://issues.folio.org/browse/MODSOURMAN-694
=> MODSOURMAN-694: Improve sql query for retrieving job execution sourcechunks

mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json
MARC 410 is mapped to sftPersonalNameTitle but should be mapped to sftCorporateNameTitle
=> MODSOURMAN-702 Change authority mapping for MARC 410

mod-source-record-manager-server/pom.xml
Bump the jackson version from 2.13.0 back to version 2.13.1.
Remove technical debt that downgrades the jackson version from 2.13.1 to 2.13.0.
Remove pom.xml entries that downgrade the jackson version provided by vertx-stack-depchain.
=> MODSOURMAN-704: jackson-databind 2.13.1 fixing DoS JsonNode issue

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/exceptions/RawChunkRecordsParsingException.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/ParsedRecordsDiErrorProvider.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/errorhandlers/ParsedRecordsDiErrorProviderTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/errorhandlers/errorpayloadbuilders/EdifactErrorPayloadBuilderTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/errorhandlers/errorpayloadbuilders/MarcBibErrorPayloadBuilderTest.java
Previously in case of some exception occurs with DB while parsing raw records - DI_ERROR have been sent, but without info about record, so as a result the final imports completes without stucking, but also without any info regarding log entries and reasons of failures.
Need to improve visibility regarding errors to the end users.
Add logic to parse records from initial raw records in error handlers 
For testing I tried to simulate by throwing RuntimeException while working with DB in some processing handler.
The UI Landing page would look like as this:
The View All page would look like as this:
The Details page (for each log entry) would look like as this:
https://issues.folio.org/browse/MODSOURMAN-699
=> MODSOURMAN-699. Can`t map 'RECORD' or/and 'MARC_BIBLIOGRAPHIC' statements from logs

mod-source-record-manager-server/src/main/resources/log4j2.properties
Reduce amount of logging of KafkaProducerConfig, KafkaConsumerConfig 
Set WARN level for Kafka ProducerConfig/ConsumerConfig messages
=> MODSOURCE-467 Set WARN level for Kafka ProducerConfig/ConsumerConfig messages

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/HrIdFieldServiceTest.java
FOLIO copies the 001 to the 035. The more times the record is re-imported, the more 035s are created.
FOLIO does not copy the 001 into the 035 again because there is not a need to construct a new 035 since the record is being being updated, not created. Once an SRS MARC Bib has an 001 that matches the Instance HRID, it should be a protected field that is never overwritten with a new number, and is not moved into an 035 field.
[MODSOURMAN-719](https://issues.folio.org/browse/MODSOURMAN-719)
=> MODSOURMAN-719 The 001 is copied to the 035 when the record is updated even though it is unnecessary

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
Support Delete MARC Authority Action
Update handling of record processing: if JobProfile contains an action for MARC_AUTHORITY delete then send DI_MARC_FOR_DELETE_RECEIVED event. 
[MODSOURMAN-691](https://issues.folio.org/browse/MODSOURMAN-691)
=> MODSOURMAN-691 Delete Authority: Support delete action and produce event

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/journal/InvoiceUtil.java
Cover more cases for showing error messages in case of Edifact import failures 
**Logs in mod-invoice:**
` CreateInvoiceEventHandler Error during invoice creation
java.util.concurrent.CompletionException: org.folio.invoices.rest.exceptions.HttpException: {"errors":[{"message":"must not be null","type":"1","code":"-1","parameters":[{"key":"vendorInvoiceNo","value":"null"}]}]}`
**View all page screen**
As you can see, in case of missing vendorReferenceNumber in profile default 0 value provided to be able to build journal records and show errors
**Details page**
**Logs in mod-invoice:**
`2022-03-17T07:53:29,671 ERROR [vert.x-worker-thread-7   ] CreateInvoiceEventHandler Error to create invoice line with number 18
java.util.concurrent.CompletionException: …
=> MODSOURMAN-722. Journal does not show error status when importing EDIFACT

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
Link should be clickable when we click, but when SRS send DI error event records without parsed record have not information about title.
- Added default title when we receive title without any data
[MODSOURMAN-724](https://issues.folio.org/browse/MODSOURMAN-724)
=> MODSOURMAN-724 SRM does not process and save error records

descriptors/ModuleDescriptor-template.json
Increase DB max connections size for Vertx connection pool from 5 to 15
Time to time we observe DB timeout issues in SRM, most often at the start of day during first import.
Connections in Vertx connection pool not always open, and when there is no application activity - connection pool can contain 0 opened connections. So this increasing of connection will not be additionally load the database when app idle, only in case of spikes
https://issues.folio.org/browse/MODSOURMAN-712
=> MODSOURMAN-712. Timeout when importing MARC files

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
The record type is determined by the seventh character. In the attached file, the 7th character is simply specified as a space.
Invalid LDR exapmle which had a space in seventh character:
=LDR 05953c m 2201213bi 4500
Before this changes we can observe strange behaviour after importing mrc files with incorrect leader:
And after changes data-import will discard records with invalid LDR:
- Checked existing leader line and MARC record type after analyzing parsed record. Set error record in the case of an incorrect LDR.
[MODSOURMAN-715](https://issues.folio.org/browse/MODSOURMAN-715)
[MODDATAIMP-654](https://issues.folio.org/browse/MODDATAIMP-654)
=> MODSOURMAN-715 marc record type NA causes data-import to not complete

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
Prevent exceptions when an event payload does not have any records in its context. This allows DI_ERROR events, that have been emitted before any records could be instantiated, to be persisted to the job execution. This provides better errors to users of Data Import.
Provide a stub record when there aren't any records in the event payload. it will be used to convey the job execution id into the journal record. A random UUID is used as the identifier of the stub record due to assumptions in DI data flow that each journal record points to a distinct source record.
The stub record is not actually stored in mod-source-record-storage.
=> MODDATAIMP-472 build journal record when no record present

descriptors/ModuleDescriptor-template.json
PgException: FATAL: password authentication failed
Increase memory in ModuleDescriptor for fix it
https://issues.folio.org/browse/MODSOURMAN-734
=> MODSOURMAN-734: Increase memory in ModuleDescriptor

NEWS.md, mod-source-record-manager-server/src/main/resources/templates/db_scripts/job_execution_source_chunks_table.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
RMB keeps trying to create FK constraint for "job_execution_source_chunks" table on old "job_executions" table, despite "fromModuleVersion" contains preceded to Lotus module version. This causes an error during upgrading the module from Lotus version to subsequent versions.
[MODSOURMAN-728](https://issues.folio.org/browse/MODSOURMAN-728)
=> MODSOURMAN-728 - Fails to upgrade from mod-source-record-manager-3.3.0-SNAPSHOT.115 to v3.3.0

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/EventDrivenChunkProcessingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/InvoiceUtil.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/is_processing_completed.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/processing_contains_error_chunks.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
Use common jobExecutionId column istead of jsonb one to speed-up performance, because when importing big files we saw, that quety took around 4 sec.
`13:45:13.477 [vert.x-worker-thread-13] WARN PostgresClient [20299737eqId] EXPLAIN ANALYZE SELECT is_processing_completed('da97355d-1eca-403d-9d7f-1eb7c36a33cc');
Result (cost=0.00..0.26 rows=1 width=1) (actual time=4079.293..4079.294 rows=1 loops=1)
Planning Time: 0.015 ms
Execution Time: 4079.320 ms` 
SQL Trigger to fill jobExecutionId was deleted recently, so INSERT query has been modified to fill this field by java code.
Also old index that pointed to jsonb filed has been deleted and new index pointing to common column jobexecutionid created.
Also in this PR we switched to use containsErrorChunks() method instead of …
=> MODSOURMAN-751. Improve sql queries to know is processing completed and is contain error chunks

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java
Not send DI_ERROR if processing of last chunk failed to avoid such screens in UI, instead use logging for last chunk processing
After fix after importing the same file UI looks like this:
Modify RawMarcChunkErrorHandler to skip sending DI_ERROR for the last chunk
https://issues.folio.org/browse/MODSOURMAN-756
=> MODSOURMAN-756. Fix unnecessary No content logs in View All page when import fails

NEWS.md, descriptors/ModuleDescriptor-template.json
Add necessary permissions for POL matching
- add permission `orders.po-lines.collection.get` to 'modulePermissions', POST method of 'source-manager-records'
- add permission `orders.po-lines.collection.get` to 'modulePermissions', PUT method of 'source-manager-parsed-records'
[MODSOURMAN-778](https://issues.folio.org/browse/MODSOURMAN-778)
=> MODSOURMAN-778 Add permission for Purchase Order Lines matching

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java
Allow instance links to be displayed in DI logs after modifying marc bib record.
Change entity type to INSTANCE for DI_SRS_MARC_BIB_RECORD_MODIFIED_READY_FOR_POST_PROCESSING event.
[MODSOURMAN-784](https://issues.folio.org/browse/MODSOURMAN-784)
=> MODSOURMAN-784 The status of instance is not updated in the Import log after uploading MARC file for modify

Jenkinsfile, README.md, ramls/change-manager.raml, ramls/metadata-provider.raml
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-source-record-manager section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config
Please fix the JSON errors, as described in the subsequent comment.
=> MODSOURMAN-776 FOLIO-3231 Use new api-lint and api-doc CI facilities

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/JobMonitoringServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/AdditionalFieldsUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/afterprocessing/AdditionalFieldsUtilTest.java
In the AdditionalFieldsUtil class, there are numerous methods used to modify/introspect MARC records. Each of these methods coverts the parsed content represented as a JSON string into a MARC4J reader to generate a MARC4J record. This conversion is compute intensive. The aim is to reduce the conversion from parsed content string to MARC4J record.
Cache MARC4J records with the originating parsed content string as its key. This cache process is not perfect but works well since any change, such as updating a subfield, generate a brand new parsed content string. Using the whole parsed content string as a key reduces the possibility of the cache returning stale data. The immutability of the String class in Java is relied upon to make this work.
The cache is limited to 25 items for now. That …
=> MODSOURMAN-791 Reduce parsed record string conversion into MARC4J record

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
MARC bib record | Source does not reflect last person to update record when the update is via data import
set userId from jobExecution to records metadata
[_MODQM-224_](https://issues.folio.org/browse/MODQM-224)
=> MODQM-224 MARC bib record | Source does not reflect last person to update record when the update is via data import

mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
To restrict update of JobExecution that is marked as "Deleted"
Update APIs requests check for the existing data and update the data with new information being sent.
In this PR, we have filtered out the deleted records, hence deleted records will not be returned and in turn, will not be updated.
=> MODSOURMAN-786 - To restrict update of JobExecution that is marked as "Deleted"

descriptors/ModuleDescriptor-template.json
to get record during update instance action profile processing
[MODINV-686](https://issues.folio.org/browse/MODINV-686)
=> MODINV-686 - Provided "source-storage.records.get" permission to get record during update instance action profile processing

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/flowcontrol/RawRecordsFlowControlServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportInitConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportInitKafkaHandler.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportInitConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleMockTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleTest.java, ramls/change-manager.raml
Due to flow control changes,  offsets of topic DI_RAW_RECORDS_CHUNK_READ consumed by batches. If next import triggers - it will not appear in Running section on UI, because job execution progress initialized after reading first chunk of DI_RAW_RECORDS_CHUNK_READ topic, so in order to see new import on UI - need to wait until all chunks of previous imports processed.
- Introduce new event DI_INITIALIZATION_STARTED (Corresponding PR: https://github.com/folio-org/data-import-raml-storage/pull/263)
- Produce this new event from mod-data-import after finding out how many records input file contains (Corresponding PR: https://github.com/folio-org/mod-data-import/pull/217)
- Initialize job execution progress and update job execution status to be visible in Running section on UI before receiving …
=> MODSOURMAN-796. Change logic to initialize job execution progress after reading file instead of processing the first chunk

mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
for ui needs (scenario 1) it is necessary to distinguish summary data for entity types that were not acted upon import to fill in columns for them with '-' character instead of '0'
return null as a summary for the type of entities that were not involved in particular import process (if summary contains only 0 values a null should be returned as entity type summary)
[UIDATIMP-1163](https://issues.folio.org/browse/UIDATIMP-1163) (scenario 1)
=> MODSOURMAN-780 - Improvement for the endpoint returning summary for work accomplished in import

NEWS.md, mod-source-record-manager-server/src/main/resources/log4j2.properties
Improve logging. Added FOLIO-approach for retrieving properties for logging.
Retreiving properties from FolioLoggingContext.
- It seems like these properties are available only for REST-requests.
- We disabled logging for REST-requests. (Just errors)
https://issues.folio.org/browse/MODSOURMAN-775
=> MODSOURMAN-775: Logs show incorrectly formatted request id.

mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/QuickMarcUpdateKafkaHandlerTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java, pom.xml
I've converted OKAPI_HEADER_TENANT in tests bellow to lower case because these [changes](https://github.com/folio-org/raml-module-builder/commit/94a085e6a71e16c71cc661fbbd59577b7ca752ca#diff-91377a3321186e8203264c2555b10f7989fad363da8ab2a3270e5ae5afad7046R37) affected to tests after upgrading rmb to 34.0.0 version.
=> MODSOURMAN-812 RMB v34 upgrade - Morning Glory 2022 R2 module release

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
to avoid returning profiles and users for filters on the "view all" page, that mentioned only in job executions marked as deleted
* filter job profiles and users by job executions that are not marked as deleted (where column "is_deleted" = false)
* add tests
[MODSOURMAN-818](https://issues.folio.org/browse/MODSOURMAN-818)
=> MODSOURMAN-818 - Improve endpoints to get job executions profiles and users

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldService.java, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/HrIdFieldServiceTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java
Data Import Updates should add 035 field from 001/003, but only for exceptional Update scenarions (in such cases records are not prior saved in SRS, where 035 fields are handled)
035 fields should also be added if other 035 fields exist in the record
Removing the creation of field 035 on the fly was erroneous because it caused an error: "MODSOURCE-521
Matching on created 035 does not work in Lotus or MG"
Remove the limitation on number of 035 fields
Construct 035 from 001 and 003 only for exceptional Update scenarios
=> MODSOURCE-521 Populate 035 fields for exceptional cases of Update action

mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/HrIdFieldServiceTest.java
SRM creates an extra 035 with hrId.
Clarification of condition for the 035 field creation: when the MARC BIB record contains the 999i subfield this means that the current record exists in DB and we don't need to generate the 035 field because of a high probability the field 001 contains hrId.
[MODSOURCE-528](https://issues.folio.org/browse/MODSOURCE-528)
=> MODSOURMAN-852: Clarification of condition for the 035 field creation

mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/HrIdFieldServiceTest.java
Adding the refinement to generate 035 was incorrect.
Data from 001 and 003 are lost when these fields were received from the vendor with previous values and field 035 with the same values already exists.
[MODSOURCE-528](https://issues.folio.org/browse/MODSOURCE-528)
=> MODSOURMAN-852: Revert changes

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/java/org/folio/mapping/DefaultRulesMappingTest.java, mod-source-record-manager-server/src/test/resources/org/folio/mapping/mappedBibRecord.json, mod-source-record-manager-server/src/test/resources/org/folio/mapping/parsedBibRecord.json
It's needed to have information if a contributor is controlled by authority
Extend bib mapping rules to map contributor's authority ID from $9 subfield
=> MODSOURMAN-858 Extend bib mapping rules to map contributor's authority ID

NEWS.md, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/main/resources/templates/db_scripts/update_source_chunks_table_structure_if_needed.sql
Update the source-chunks table to make it consistent between clean deployment and non-clean. It was caused because we changed the creation of this table - now, it will create not via RMB.
Added trigger and functions.
JIRA: https://issues.folio.org/browse/MODSOURMAN-833
=> MODSOURMAN-833: Schema differences between MG Bugfest and clean MG deployment: mod-source-record-manager.

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/mappers/processor/MappingParametersProviderTest.java
Populate Authority Source Files from mod-inventory-storage in MappingParametersProvider.
[MODSOURMAN-866](https://issues.folio.org/browse/MODSOURMAN-866)
- getAuthoritySourceFiles method added to MappingParametersProvider
- Permissions added to ModuleDescriptor
- Tests updated
=> MODSOURMAN-866 Assign each authority record to an Authority Source file list

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_index_on_job_execution_started_date.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
Started date for jobs was added on Landing page, sorting should also be possible
Extend enum of sortable fields for jobExecutions
=> MODSOURMAN-868 Allow sorting of JobExecutions by started_date

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
To avoid invalid validation if MARC_BIB Holdings(not MARC-Holdings) wanna be created.
Added additional condition to retrieve needed field from mapping profile.
JIRA: https://issues.folio.org/browse/MODSOURMAN-874
=> MODSOURMAN-874: Data import: fails the creation of a Holding through a match on the 999 ff field

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json
to update the default mapping rule of the 590 field to mapp a note as stuff only, if ind1 = 0
[MODSOURMAN-827](https://issues.folio.org/browse/MODSOURMAN-827)
=> MODSOURMAN-827 - Updated mapping rules of 590 field for "staff only"

mod-source-record-manager-server/pom.xml
Upgrade folio-di-support from 1.4.1 to 1.6.0.
This indirectly upgrades spring-beans from 5.2.8.RELEASE to 5.3.20 fixing Spring4Shell Remote Code Execution vulnerability, for details see https://issues.folio.org/browse/FOLIO-3466 and
https://nvd.nist.gov/vuln/detail/CVE-2022-22965 .
The Spring upgrade also fixes these vulnerabilities:
https://nvd.nist.gov/vuln/detail/CVE-2021-22060
https://nvd.nist.gov/vuln/detail/CVE-2021-22096
https://nvd.nist.gov/vuln/detail/CVE-2022-22968
https://nvd.nist.gov/vuln/detail/CVE-2022-22950
https://nvd.nist.gov/vuln/detail/CVE-2022-22970
For each flower release each module should upgrade all dependencies.
=> MODSOURMAN-889: folio-di-support 1.6.0 fixing Spring4Shell

descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDao.java, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MappingMetadataProviderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/MappingMetadataService.java, mod-source-record-manager-server/src/main/java/org/folio/services/MappingMetadataServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/mappingMetadataProvider/MappingMetadataProviderAPITest.java, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_mapping_params.json, ramls/mapping-metadata-provider.raml
Purpose
As described in MODSOURMAN-888, implemented API endpoint to retrieve mapping metadata by record type
Approach
- Extend mapping-metadata-provider API interface with new endpoint (permission could be same)
- Use QueryPathUtil.toRecordType for record-type conversion
- Load mapping rules from the database and mapping metadata from a local cache
Learning
https://issues.folio.org/browse/MODSOURMAN-888
=> MODSOURMAN-888 - Link update: Implement API endpoint to retrieve mapping metadata by record type

NEWS.md, RuleProcessorApi.md, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json
To map  specific  MARC fields  to instance contributor. 
For subfield "e" as name:
- 100
- 110
- 700
- 710
For subfield "j" as name:
- 111
- 711
* add marc-bib mapping rule for these fields
* documentation for "alternativeMapping" added.
[MODSOURMAN-837](https://issues.folio.org/browse/MODSOURMAN-837)
=> MODSOURMAN-837:MARC bib - FOLIO instance mapping | Update default mapping to change how Relator term is populated on instance record

NEWS.md, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
Avoid situations when 2 or more actions were processed for the 1 Instance - calculate it as 1 Instance.
Improved script via distinct by entity_id.
https://issues.folio.org/browse/MODSOURMAN-907
=> MODSOURMAN-907: The '2' number of Instance is displayed in cell in the row with the 'Updated' row header at the individual import job's log

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java
https://issues.folio.org/browse/MODSOURMAN-891
Overview: When you want to create either a holdings connected to an existing instance or an item connected to an existing holdings, you match to either that holdings hrid or instance hrid and have an action to create either the holdings or item. What is happening is that the holdings and items are created AND the log also says the SRS MARC is created.
Current workaround: No workaround
Steps to Reproduce:
Log into FOLIO-snapshot as diku_admin
Go to Settings/Data Export
Create a new mapping
SRS and Holdings
Map Holdings HRID to 901$a
Map Holdings Id to 902$a
Create a new data export job linked to that mapping
Go to Settings/Data Import
Create a new field mapping for an item
Item mat type: Electronic resource
Loan type: Online
Status: Available …
=> [MODSOURMAN-891]SRS MARC Created when No Create Action in Job Profile

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
Overview: The POST request for the endpoint "/records-editor/records" is failed with the "500" error when user creates the "MARC Holdings" record.
Steps to Reproduce:
Log into Snapshot-2 / Nolana BF FOLIO environment as User with the following permissions: 
Inventory: All permissions
quickMARC: View, edit MARC holdings record,
quickMARC: Create a new MARC holdings record.
The detail view of "Instance" record with source = "MARC" has been opened at the third pane via "Inventory" app.
Click on the "Actions" button and select the "Add MARC holdings record" option from the expanded dopdown.
Fill in "852" subfield with $b value (any), by clicking on "Permanent location look-up" button and choose values from the dropdown lists for "Institution", "Campus", "Library", "Location" >> Click on the …
=> [MODSOURMAN-920]The "500" error appears when user creates "MARC Holdings" record

NEWS.md, mod-source-record-manager-client/pom.xml, mod-source-record-manager-server/pom.xml, pom.xml
https://issues.folio.org/browse/MODSOURMAN-923
Upgrade Spring from 5.2.8.RELEASE to 5.2.22.RELEASE fixing Spring4Shell (https://github.com/advisories/GHSA-36p3-wjmg-h94x).
Release mod-source-record-manager v3.4.6 as Morning Glory Hot Fix.
=> MODSOURMAN-923: Release v3.4.6 with Spring 5.2.22 fixing Spring4Shell (MG)

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODSOURMAN-930
After updating implementation of creating invoice flow the permissinon set has been updated. In order to support these changes in invoice data import flow the permission set in mod-data-source-manager should be updated as well.
Following permissions should be added:
"orders-storage.order-invoice-relationships.item.post",
"finance-storage.budget-expense-classes.collection.get",
"finance.ledgers.collection.get",
"finance.funds.budget.item.get",
"finance-storage.fiscal-years.item.get",
"finance.fiscal-years.item.get",
"finance-storage.budgets.collection.get",
"finance.transactions.collection.get",
"finance.expense-classes.collection.get",
"finance.exchange-rate.item.get"
=> [MODSOURMAN-930]Add missed permissions for invoice data import flow

mod-source-record-manager-server/src/main/java/org/folio/services/MappingRuleServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/util/EventHandlingUtil.java, mod-source-record-manager-server/src/main/resources/log4j2-json.properties, mod-source-record-manager-server/src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODDATAIMP-758HAide SQL requests (org.folio.rest.persist.PostgresClient) from log files for the next modules:
mod-data-import
mod-source-record-storage
mod-data-import-converter-storage
mod-inventory-storage
This class logs SQL queries at the INFO level, which leads to a very large size of log files.
SRS: a lot of messages like this:
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.protocol' was supplied but isn't a known config.
....
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.truststore.type' was supplied but isn't a known config.
SRM: move to TRACE level or decrease defaultRules json
2023-01-05 01:55:50.850 [vert.x-eventloop-thread-1] [572525/proxy;692150/tenant] [diku] [] [mod_source_record_manager] DEBUG …
=> [MODDATAIMP-758]Imrove logging (hide SQL requests)

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java
to save information to the data import log about inventory records (instance, holdings, item) creation on receiving "DI_ORDER_READY_FOR_POST_PROCESSING" event.
* expand JournalParamsEnum with logic to return journal params based on the last event. If a last event is not related to instance/holdings/item creation, then don't save info to import journal
* add tests
[MODSOURMAN-936](https://issues.folio.org/browse/MODSOURMAN-936)
=> MODSOURMAN-936 - Add logic in Journal Handler for DI_ORDER_READY_FOR_POST_PROCESSING event 

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunkConsumersVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java
To differentiate the flow of importing Orders from regular DI, when MARC Bibs are saved in SRS a different event should be issued to be received by mod-orders. SRM should publish DI_MARC_BIB_FOR_ORDER_CREATED. Event type should be determined based on the action for creating Orders in the JobProfileWrSnapshotWrapper retrieved from JobExecution.
Get JobExecution from DB and retrieve JobProfileSnapshotWrapper from it. If there is action on Order+Create, then set eventType for sending "DI_MARC_BIB_FOR_ORDER_CREATED"
JIRA: https://issues.folio.org/browse/MODSOURMAN-937
=> MODSOURMAN-937: Send DI_MARC_BIB_FOR_ORDER_CREATED event for Importing Orders

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
Return count of all PO_LINE for order summary (not group by orderId)
(https://issues.folio.org/secure/attachment/52792/UIDATIMP-1264%20Mockup.png)
Removed DISTINCT(orderId) from get_job_execution_summary function
=> [MODSOURMAN-932] Return count of all PO_LINE in order summary

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDao.java, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/JournalRecordService.java, mod-source-record-manager-server/src/main/java/org/folio/services/JournalRecordServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java, mod-source-record-manager-server/src/test/java/org/folio/dao/JournalRecordDaoTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/EventTypeHandlerSelectorTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java
The main purpose is to handle DI_ERROR for Order/PO_Line importing for updating journal_record errors.
There are two scenarios:
1. Update all records where entityType = PO_LINE and orderId = "{orderId}" and add current one with the same data.
2. Create only one record if  "orderId==null" and write the current record with the error message from the payload.
JIRA: https://issues.folio.org/browse/MODSOURMAN-946
=> MODSOURMAN-946: Handle DI_ERROR event for POLines

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JobExecutionUtils.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandlerTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java
https://issues.folio.org/browse/MODSOURMAN-899
Currently, when a user cancels job DI continues to process chunks related to this job.
In RawMarcChunksKafkaHandler and StoredRecordChunksKafkaHandler get jobExecutionId from Kafka headers, check JobExecution status, if canceled or deleted (empty result) - skip processing of the chunk (DI_ERROR messages NOT needed) without deserializing (unpacking) the chunks.
Check impact on job progress tracking - add same logic in DataImportKafkaHandler (DI_COMPLETE and DI_ERROR messages). Check behavior of FlowControl, create separate task to resolve any issues.
This method will increase the performance of the DI and reduce the load on the CPU.
=> [MODSOURMAN-899]Do not process chunks when the DI is stopped

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDao.java, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionProgressDao.java, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionProgressDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java, mod-source-record-manager-server/src/main/java/org/folio/services/progress/JobExecutionProgressServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-orders module needs actual incoming total records amount to calculate expected po lines amount to be processed for particular order before opening it during orders import
* add method into JobExecutionDao to update job progress with actual records amount directly in the jobExecution table
* refactor JobExecutionProgressDaoImpl::initializeJobExecutionProgress() method to be executed in scope of the outer transaction
* update jobExecution with actual records amount after import progress is initiated within the same transaction
* update tests
[MODSOURMAN-961](https://issues.folio.org/browse/MODSOURMAN-961)
=> MODSOURMAN-961 - Provide actual incoming records amount on request jobExecution by id

descriptors/ModuleDescriptor-template.json
Move linking-rules interface dependency from "required" to optional
Move linking-rules interface dependency from "required" to optional
[MODSOURMAN-974](https://issues.folio.org/browse/MODSOURMAN-974)
=> MODSOURMAN-974 MARC bib $9 handling | Remove $9 subfields from linkable fields

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/metadata-provider.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODSOURMAN-988 Use GitHub Workflows api-lint and api-schema-lint and api-doc

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/RecordProcessedEventHandlingServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java
One event would be issued when multiple Holdings or Items were created, DI should also support partial success - in case at least one of the Holdings or Items were created/updated, further processing of the profile for the given record should be continued. Therefore, DI_COMPLETED event payload will contain a list of successfully created entities and a list of errors. In case at least one of the entities failed to be created/updated it should be counted as an error upon completion.
Added logic in RecordProcessedEventHandlingServiceImpl to check payload of DI_COMPLETED event and count it as an error in case at least one error present (there is something by the key ERROR in the event payload)
JIRA: https://issues.folio.org/browse/MODSOURMAN-965
=> MODSOURMAN-965: Adjust progress tracking mechanism with regard to multiple values being created

mod-source-record-manager-server/src/main/resources/rules/marc_holdings_rules.json, mod-source-record-manager-server/src/test/java/org/folio/mapping/DefaultRulesMappingTest.java, mod-source-record-manager-server/src/test/resources/org/folio/mapping/mappedHoldingsRecord.json
Fix bug when call number type doesn't map from MARC
The mapping processor did not process the call-number-type rule because it requires the presence of subfields in the rule. If there are no subfields, the rule is skipped. To resolve this issue, I have added a reference to the "b" subfield, as it is required for Holdings records.
=> MODSOURMAN-990 Fix call number type doesn't map from MARC

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineService.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingService.java, mod-source-record-manager-server/src/main/java/org/folio/services/EventDrivenChunkProcessingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/ParsedRecordsDiErrorProvider.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/errorhandlers/ParsedRecordsDiErrorProviderTest.java, ramls/change-manager.raml
Instances need to be created by Data Import(DI) with a known identifier to realize ECS. For local instance that have source=MARC, DI will create the Shared Instance in the central tenant. The Shared instance needs to be created with the same identifier as the local instance that is being promoted
This is not currently allowed in DI. A query parameter will be added to signal to DI to allow the 999ff$i field to be set and also create an instance with value in 999ff$i.
Query parameter will be accepted when initializing a data import at /change-manager/jobExecutions/<id>/records
Query parameter will be called acceptInstanceId and settable to true/false with a default of false.
[MODSOURMAN-1011](https://issues.folio.org/browse/MODSOURMAN-1011)
=> MODSOURMAN-1011: Import An Instance With A Known Identifier

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
_Add support for a single holding which comes from mod-inventory while journaling._
_Currently mod-inventory sends a single holding as JsonObject so SRM should handle both cases single and multiple_
=> MODSOURMAN-1031: Add support for a single holding

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/RawMarcChunkConsumersVerticle.java
Introduce global backpressure to kafka consumers for the whole application. This will limit the number of "concurrent" messages that can be processed by SRM. This will reduce contention on the database connection pool which yields timeout errors during high load.
Update the back pressure gauge to consider the global load sensor. Also disable global load sensing for the consumer responsible for raw records processing since the Flow control service in SRM is responsible for managing raw records processing.
=> MODSOURMAN-1029 introduce global backpressure to kafka consumers

descriptors/ModuleDescriptor-template.json
Fix circular dependency mod-entities-links and mapping-rules.get
Make mod-entities-links interfaces optional
=> MODSOURMAN-1039 Fix circular dependency mod-entities-links and mapping-rules.get

descriptors/ModuleDescriptor-template.json
Error is 'org.folio.inventory.consortium.exceptions.ConsortiumException: Error retrieving centralTenantId by tenant id: diku, status code: 403, response message: Access for user 'cypressTestUser673.2125076239648903' (56b0edf3-9064-4bd5-9466-272de43a97de) requires permission: user-tenants.collection.get'.{}
Added permissions for user-tenants collection
=> [MODINV-873] Add permissions for user tenants collection

mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
_`holdingsId` should be present for every item in `relatedItemInfo`._
_Set a proper name for holdings id key that comes from mod-inventory_
=> MODSOURMAN-1037: Get holdings id key according to mod-inventory payload

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java
Allow create action when non-matches for instance
The validation condition is updated to check whether non-match operation is processed
=> MODSOURMAN-1003: Allow create action when non-matches for instance

.vscode/settings.json, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
When a composite job's child completes, we may need to mark its parent as completed, too.  This was done as part of the normal processing flow [here](https://github.com/folio-org/mod-source-record-manager/blob/6f135cae9f91c1a773631c134385d0182990a816/mod-source-record-manager-server/src/main/java/org/folio/services/RecordProcessedEventHandlingServiceImpl.java#L124), however, we should also do this upon external status changes from the `status` endpoint.
This adds similar code as what is in `RecordProcessedEventHandlingServiceImpl`: when the update status method is called, we will first check that the updated job is a composite child; if so, we'll check that its siblings have all completed; and if all those conditions apply, we'll mark the parent `COMMITTED`/`RUNNING_COMPLETE`.
- Cleaned …
=> [MODSOURMAN-1041] Check for composite completion upon external status updates

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java
Allow create action when non-matches for instance without match profile
In cases when there is no a match profile `reactTo` is `null` therefore it should be handled properly to construct `ParsedResult` with errors for such a case.
[MODSOURMAN-1045](https://issues.folio.org/browse/MODSOURMAN-1045)
=> MODSOURMAN-1045: allow create action when non-matches for instance

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/util/EventHandlingUtil.java
Upgrade folio-kafka-wrapper to 3.0.0 version
Upgrade the version of folio-kafka-wrapper to 3.0.0. Check out the readme at https://github.com/folio-org/folio-kafka-wrapper/blob/master/README.md for usage.
Acceptance Criteria
- kafka records are built using KafkaProducerRecordBuilder
- topic names are generated using KafkaTopicNameHelper
=> MODSOURMAN-1014: Upgrade folio-kafka-wrapper to 3.0.0 version

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionFilter.java, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/RecordProcessedEventHandlingServiceImpl.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/alter_job_executions_table_for_chunk_support.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/alter_job_executions_table_for_total_records.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/dao/JobExecutionDaoImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, ramls/metadata-provider.raml
Merge changes from the DITF to support DI file slicing. This required changing logic in SRM to add a new job types `COMPOSITE_PARENT` and `COMPOSITE_CHILD`, as well as some additional job execution fields to support these associations.
By adding new DB fields to support these values as well as logic to support associations between the parent and children chunks (e.g. finishing the last child => the parent is finished).
=> [MODSOURMAN-1049] DITF forward merge

NEWS.md, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JournalRecordsColumns.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
to provide marc record and instance on the log page with json when marc-to-marc matching and marc update has been performed on the central tenant by data import initiated on a member tenant
* save central tenant id into the "journal_records" table upon receiving event when the event payload contains it
* populate central tenant id into the "sourceRecordTenantId" and "relatedInstanceInfo.tenantId" fields in the response of the GET /metadata-provider/jobLogEntries/{jobExecutionId}/records/{recordId} endpoint 
* add tests
[MODSOURMAN-1044](https://issues.folio.org/browse/MODSOURMAN-1044)
Requires: https://github.com/folio-org/data-import-raml-storage/pull/299
=> MODSOURMAN-1044 - Adjust logs during marc-to-marc matching on central tenant

mod-source-record-manager-server/src/main/resources/log4j2-json.properties, mod-source-record-manager-server/src/main/resources/log4j2.properties
Default log configuration is way too verbose
Returned INFO level except DEBUG
[MODSOURMAN-1064](https://issues.folio.org/browse/MODSOURMAN-1064)
=> MODSOURMAN-1064: Default log configuration is way too verbose

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
[MODSOURMAN-1082](https://issues.folio.org/browse/MODSOURMAN-1082)
Fix issue with log details not shown for errors occurred prior to matching
Log details were not shown because journal records were not saved for case when error happened prior to matching. Handled this case and now the log details and errors are shown, ex.:
=> MODSOURMAN-1082 fix log details not shown for errors occurred prior to matching

mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java
Jobs with parsing errors fail for Update scenarios, because Error payload cannot be constructed if RecordType is undefined
Make sure DI_ERROR event is sent even if RecordType is undefined
For scenarios when records are first saved in SRS, RecordType is defaulted to MARC_BIB. Not sure that's how it is supposed to be, but since we are removing the step of saving records in SRS, I don't think we should change it at this point
=> MODSOURMAN-1066 Fix hanging of the job with parsing errors for update scenarios

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/dao/IncomingRecordDao.java, mod-source-record-manager-server/src/main/java/org/folio/dao/IncomingRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/IncomingRecordService.java, mod-source-record-manager-server/src/main/java/org/folio/services/IncomingRecordServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/dao/IncomingRecordDaoImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/IncomingRecordServiceImplUnitTest.java, ramls/metadata-provider.raml
Provide IncomingRecord API
Add endpoint to get IncomingRecord by ID with DAO and service layers functionality
=> MODSOURMAN-1021: Add endpoint for IncomingRecord 

NEWS.md, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
The number of updated records is not correct displayed in the 'SRS Marc' column in the 'Log summary' table
Change the script function which creates get_job_execution_summary, so all journal records with action status 'UPDATE' can be viewed.
Step of reproducing this issue: [MODSOURMAN-1030](https://issues.folio.org/browse/MODSOURMAN-1030).
=> MODSOURMAN-1030: The number of updated records is not correct displayed in the 'SRS Marc' column in the 'Log summary' table

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/dao/IncomingRecordDao.java, mod-source-record-manager-server/src/main/java/org/folio/dao/IncomingRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/IncomingRecordService.java, mod-source-record-manager-server/src/main/java/org/folio/services/IncomingRecordServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/dao/IncomingRecordDaoImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/IncomingRecordServiceImplUnitTest.java, ramls/metadata-provider.raml
Provide IncomingRecord API
Add endpoint to get IncomingRecord by ID with DAO and service layers functionality
=> MODSOURMAN-1021: add endpoint to get IncomingRecord by id

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunkConsumersVerticleTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java
Remove step of initial saving of incoming records to SRS
Removing step of initial saving of incoming records to SRS and using `RecordsPublishingServiceImpl` to send events into `DI_INCOMING_EDIFACT_RECORD_PARSED` and `DI_INCOMING_MARC_BIB_RECORD_PARSED` topics
[MODSOURMAN-1022](https://issues.folio.org/browse/MODSOURMAN-1022)
=> MODSOURMAN-1022: remove step of initial saving of incoming records to SRS

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java
The '1' number of Instance is displayed in cell in the row with the 'Updated' row header at the individual import job's log
Removed DI_SRS_MARC_BIB_RECORD_MODIFIED_READY_FOR_POST_PROCESSING subscription.
[MODSOURMAN-1091](https://issues.folio.org/browse/MODSOURMAN-1091)
=> MODSOURMAN-1091: Fixed improper behavior during instance subscription in MARC Bib Modify action

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json
MARC record with a 100 tag without a $a is being discarded on import. [MODSOURMAN-1085](https://issues.folio.org/browse/MODSOURMAN-1085) 
mark a subfield as requiredSubfield
tests were fixed, test case was added into di-processing-core
currently in requiredField section the logical relation between subfields are "and".
=> MODSOURMAN-1085 MARC record with a 100 tag without a $a is being discarded on import.

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java
MARC authority record is not created when use Job profile with match profile and action only on no-match branch. 
[MODSOURMAN-1108](https://issues.folio.org/browse/MODSOURMAN-1108)
* replace condition for checking update action with match profile exist
* add test case
* fix tests
=> MODSOURMAN-1108 MARC authority record is not created when use Job profile with match profile and action only on no-match branch

descriptors/ModuleDescriptor-template.json
Accomodate for authority-source-files api changes
Update authority-source-files interface version, use updated dto from data-import-processing core
=> MODSOURMAN-1115 Accomodate for authority-source-files api changes

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
Remove entity type set for journal records to not fetch them with `get_job_log_entries`
=> MODSOURMAN-1063: remove entity type set for journal records 

descriptors/ModuleDescriptor-template.json
Add permissions for creating/updating MARC Bib by DI
Add following permissions:
- source-storage.records.post
- source-storage.records.put
In mod-source-record-manager for:
- /change-manager/jobExecutions/{id}/records 
- /change-manager/parsedRecords/{id}
=> [MODDATAIMP-983] Add permissions for creating/updating MARC Bib by DI

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java
To avoid Exception in FAT-tests.
Additional check added
JIRAs:
https://issues.folio.org/browse/FAT-11415
https://issues.folio.org/browse/MODSOURMAN-1122
=> MODSOURMAN-1122: Additional check added.

NEWS.md, README.md, mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/main/java/org/folio/services/kafka/SRMKafkaTopicService.java, mod-source-record-manager-server/src/main/java/org/folio/services/kafka/support/SRMKafkaTopic.java, mod-source-record-manager-server/src/main/resources/kafka.properties, mod-source-record-manager-server/src/test/java/org/folio/services/KafkaAdminClientServiceTest.java
Create Kafka topics instead of relying on auto create in mod-srm [MODSOURMAN-1123](https://issues.folio.org/browse/MODSOURMAN-1123)
* create kafka topics when tenant init
* add test
=> MODSOURMAN-1123 Create Kafka topics instead of relying on auto create in mod-srm

NEWS.md, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
Fix Kafka test failures in ChangeManagerAPITest [MODSOURMAN-1139](https://folio-org.atlassian.net/browse/MODSOURMAN-1139)
add awaitility to wait for event to be received
=> MODSOURMAN-1139 Fix Kafka test failures in ChangeManagerAPITest

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/AdditionalFieldsUtil.java
Data import fails for MARC authority record if it was previously imported
When adding a new field, the cache based on the old parsed content should be invalidated
=> MODSOURMAN-1140 Invalidate cache before saving new parsed content

mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
Change get_job_log_entries sql function to retrieve sourceRecordId from existing bib
- Update get_job_log_entries function to retrieve sourceRecordId from existing journal_record on MARC_BIB, or MARC_AUTHORITY, or MARC_HOLDING
- Updated logic for multiple holdings and item entries log formation
- Updated test
=> [MODSOURMAN-1141] Change get_job_log_entries sql function to retrieve sourceRecordId from existing bib

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
Fix a validation error when trying to import a .mrc-file with a record that has 999ff fields with this Job Profile: 
1) Modify Action Profile to remove 999 field
2) Create Instance Action Profile .
Remove 999fi validation for the instance, and move it to the Instance creation step.
[MODDATAIMP-1001](https://folio-org.atlassian.net/browse/MODDATAIMP-1001)
=> MODDATAIMP-1001 Data import profile - incoming record contains 999

mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/AdditionalFieldsUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/afterprocessing/AdditionalFieldsUtilTest.java, mod-source-record-manager-server/src/test/resources/org/folio/services/parsedRecords/parsedRecord.json, mod-source-record-manager-server/src/test/resources/org/folio/services/parsedRecords/reorderedParsedRecord.json, mod-source-record-manager-server/src/test/resources/org/folio/services/parsedRecords/reorderingResultRecord.json
Keep 00X field's  position when Creating/Deriving/Editing MARC records
Implemented  reorderMarcRecordFields method to keep right order of MARC records
Closes: MODSOURMAN-1137
=> MODSOURMAN-1137: keep 00X field's  position when Creating/Deriving MARC records

descriptors/ModuleDescriptor-template.json
(ECS) The 'source-storage.snapshots.post' permission is absent
Added permission 'source-storage.snapshots.post' to /change-manager/jobExecutions/{id}/records endpoint
[MODSOURMAN-1162](https://folio-org.atlassian.net/browse/MODSOURMAN-1162)
=> MODSOURMAN-1162: (ECS) The 'source-storage.snapshots.post' permission is absent

NEWS.md, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java
Records are not displayed under their original numbers and are constantly changing by places
Adjusted log entries script including not null entiy id
[MODSOURMAN-1151](https://folio-org.atlassian.net/browse/MODSOURMAN-1151)
=> MODSOURMAN-1151: Records are not displayed under their original numbers and are constantly changing by places

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json
Update default mapping rule to include mapping for Cancelled LCCN
Updated default mapping to include mapping for Cancelled LCCN
[MODSOURMAN-1120](https://folio-org.atlassian.net/browse/MODSOURMAN-1120)
=> MODSOURMAN-1120: Updated default mapping to include mapping for Cancelled LCCN

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
Adjust job execution summary table to count MATCH action
- Count 'MATCH' journal_record as 'NO ACTION'
- Retrieve 'MATCH' record only if no other record with different action type
=> [MODSOURMAN-1168] Adjust job execution summary table to count MATCH action

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql, mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java
When the entity matched and no action is performed, should be shown status 'No action' for the underlying entity
- Modified JournalUtil logic to save journal_record for match action for marc bib/instance
- Modified get_job_log_entries and get_record_processing_log functions to return Discarded for MATCH journal record if no other record with other status exists
=> [MODSOURMAN-1134] Fix No action status on entities match and no action

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
The 'User' filter is not updated after logs deletion
- Adjusted condition for retrieving unique users;
- Added test case to ignore composite parent during retrieving unique users.
=> MODSOURMAN-1176 The 'User' filter is not updated after logs deletion

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java
to avoid row duplication in the main table on the import job logs page for the case of order and instance import import
when imported order and imported instance contain different title
* populate title for order line journal record with extracted data from MARC record field in compliance with marc bib mapping rules
* update test
[MODSOURMAN-1185](https://issues.folio.org/browse/MODSOURMAN-1185)
=> MODSOURMAN-1185 - Logs are duplicated on the import logs page for order import

mod-source-record-manager-server/src/test/java/org/folio/rest/impl/mappingRulesProvider/MappingRulesProviderAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/KafkaAdminClientServiceTest.java
Reduce flaky tests
disable a test asserting authority rules until an approach is determined and also derive topics name dynamically from utility functions.
=> MODDICORE 405 Fix Flaky Tests

mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java
Fix failed karate tests 
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioQualityGates/job/folioCiQualityGates/496/cucumber-html-reports/report-feature_206_3207137523.html
Do not form redundant null journal record during transform of PO_LINE event
=> [FAT-16007] Do not form redundant null journal record during transform of PO_LINE event

NEWS.md, mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java, pom.xml
fix duplicate job log entries after update holdings and items with cascading profiles [MODINV-1069](https://folio-org.atlassian.net/browse/MODINV-1069)
fix function job_log_entries
=> Fix DataImportConsumerVerticleTest in mod-inventory and Fix NPE in HoldingsItemMatcher, fix job log entries

mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/payloadbuilders/MarcAuthorityDiErrorPayloadBuilder.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/errorhandlers/errorpayloadbuilders/MarcAuthorityPayloadBuilderTest.java
Marc authority records with 999$f field are not displayed after importing file for creating records
Set null parsed record for MARC_AUTHORITY parsing error journal record
https://folio-org.atlassian.net/browse/MODSOURMAN-1219
=> [MODSOURMAN-1219] Set null parsed record for MARC_AUTHORITY di error journal record

descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json
The main goal is to fix the behavior when new "Subject" doesn't display in Instance detail when it was added via quickmarc/data import update action.
Mapping rules improved.
This PR should be merged after this one will be merged: https://github.com/folio-org/data-import-processing-core/pull/361
JIRA: https://folio-org.atlassian.net/browse/MODSOURMAN-1226
=> MODSOURMAN-1226: New "Subject" doesn't display in Instance detail when it was added via quickmarc/data import update action

mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json
When user importing file with the wrong second identificator for subject source field after the import on Instance subject type field disappear either.
Added subject.type rule for default indicators
https://folio-org.atlassian.net/browse/MODSOURMAN-1227
=> [MODSOURMAN-1227] Allow subject type be mapped if second id is incorrect

NEWS.md, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/mappingMetadataProvider/MappingMetadataProviderAPITest.java, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json
Adjust mapping of subject source field by using a code from subfield 2 for the case when ind2 = 7
* updated mapping rules for subject source field for being mapped using a value from $2 subfield
[MODDICORE-415](https://folio-org.atlassian.net/browse/MODDICORE-415)
Requires: https://github.com/folio-org/data-import-processing-core/pull/366
=> MODDICORE-415 - Adjust mapping of Subject source specified in subfield 2

NEWS.md, RuleProcessorApi.md, descriptors/ModuleDescriptor-template.json, mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java, mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java, mod-source-record-manager-server/src/test/java/org/folio/services/mappers/processor/MappingParametersProviderTest.java, mod-source-record-manager-server/src/test/resources/org/folio/mapping/mappedBibRecord.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json, mod-source-record-manager-server/src/test/resources/org/folio/services/marc_mapping_params.json
The main purpose is to update default mapping for Date type, Date 1, and Date 2 fields
So there should be extended our default mapper. Previouslym we did NOT map simple JsonObjects, just String or Arrays. In our case, the "Dates" - is an object, and our mapper can't work with this type of Instance's field. So there was added a new property to rules named "createSingleObject". And if mapper find this rules - it will handle this rule via specific logic, building rules into 1 JsonObject. 
1. Mapping parameters extended via new Date data.
2. Default Mapping rules improved for 008 field.
3. Tests improved.
4. New permissions added.
5. Documentation for mapping rules extended via new property.
JIRA: https://folio-org.atlassian.net/browse/MODSOURMAN-1228
**NOTE**: This PR should be merged …
=> MODSOURMAN-1228: Update default mapping for Date type, Date 1, and Date 2 fields

descriptors/ModuleDescriptor-template.json
[MODDATAIMP-1100](https://folio-org.atlassian.net/browse/MODDATAIMP-1100)
Data-import karate tests falls into infinity loop, breaking CI Quality Gates pipeline
Add missing permissions
Old permission | New permissions
-- | --
data-import.uploaddefinitions.get | data-import.uploadDefinitions.item.get, data-import.uploadDefinitions.collection.get
data-import.uploaddefinitions.files.post | data-import.uploadDefinitions.files.item.post, data-import.uploadDefinitions.processFiles.item.post
data-import.fileExtensions.get | data-import.fileExtensions.item.get, data-import.fileExtensions.collection.get
data-import.fileExtensions.default | data-import.fileExtensions.default.post
data-import.uploadUrl.get | data-import.uploadUrl.item.get, data-import.uploadUrl.subsequent.item.get …
=> MODDATAIMP-1100 Fix permissions

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java
DI log is not opened on UI and data is not written to the database
Added DI_MARC_FOR_UPDATE_RECEIVED log message handling
=> MODSOURMAN-1249: "SRS MARC" and "Authority" tabs are empty in data import of MARC authority log

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/verticle/JobExecutionProgressVerticle.java, mod-source-record-manager-server/src/test/java/org/folio/verticle/JobExecutionProgressVerticleTest.java
The main goal is to send "DI_JOB_COMPLETED" event even if SPLIT_FILE is disabled on the environment.
Additional condition on sending event added if subordination type for job = CHILD or PARENT_SINGLE
Test added.
JIRA: https://folio-org.atlassian.net/browse/MODSOURMAN-1266
=> MODSOURMAN-1266: FIX - Event DI_JOB_COMPLETED is not being sent upon the completion of the data import process on snapshot, snapshot-2

README.md, mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java
[MODDATAIMP-1135](https://folio-org.atlassian.net/browse/MODDATAIMP-1135) Log entries are empty for completed jobs
* save journal recs by job id
* group journal records by job execution id to reduce chances of deadlock in the database. 
* Also modified DataImportJournalBatchConsumerVerticle to be resilient to errors and continue processing without restarting the service.
=> MODDATAIMP-1135 Log entries are empty for completed jobs

mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java
during autoscaling of mod-srm sometimes mod-srm's consumer fails to join cg (for ex. due to network slowness, partition, etc)
we end up having 2 module instances, but one consumer, during downscaling when the load is normalized instance is destroying consumer in consumer group, as its been specified in its logic, so at the end no consumer is left, although one instance of mod-srm is up and running
* increase max pool timeout
* remove consumer clean-up logic (since its will be handled by broker itself)
* poll for records when module is facing rebalanceInProgressException
=> MODSOURMAN-1268 - Log entries are empty for completed jobs

mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java, mod-source-record-manager-server/src/main/resources/log4j2-json.properties, mod-source-record-manager-server/src/main/resources/log4j2.properties
in the previous approach, we were waiting, polling, and then committing offsets if a  rebalance exception occurred in the commitOffsets logic 
now, we wait then retry commit without polling for new records
also other error are handled in similar fashion
=> Remove polling when RebalanceInProgressException occured during consumption of events 

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_insert_journal_records_function.sql
in insert_journal_records we were not specifying column orders when making insert query
since on sprint-testing source-record-order column placed in different position than on dev-rancher env casting were not working properly 
specify name of the columns during insert command
=> fix insert script when batch insert

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java, mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
This pull request addresses several enhancements and fixes related to journal record creation logic, particularly concerning error handling and event processing for MARC and Instance entities. It includes improvements in robustness, maintainability, and clarity of the `buildJournalRecordsByEvent` method, while resolving specific cases of MARC and Instance record handling.
- Ensures that journal records for MARC entities are populated correctly when errors occur on an Instance that lacks MARC_BIB context.
- **Modularization:** Extracted complex conditional logic into dedicated helper methods, significantly improving readability, maintainability, and testing capabilities.
- **Introduced `ProcessEntityContext` Record:**
- Consolidates related contextual parameters into a single data …
=> [MODSOURMAN-1304] Instance Record Creation for MARC_BIB  

mod-source-record-manager-server/pom.xml, mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java, mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java
to configure "group.instance.id" property during consumer wrapper creation
[MODSOURMAN-1341](https://issues.folio.org/browse/MODSOURMAN-1341)
=> MODSOURMAN-1341 - Set groupInstanceId property during consumer wrapper creation

NEWS.md, mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java, mod-source-record-manager-server/src/main/java/org/folio/services/progress/JobExecutionProgressServiceImpl.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java, mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
to ensure inclusion of jobExecutionId in the message headers for import processes initiated through the mod-source-record-manager API, to allow the skipping of messages related to canceled jobs using the jobExecutionId from the message headers.
[MODSOURCE-747](https://issues.folio.org/browse/MODSOURCE-747)
=> MODSOURCE-747 - Ensure jobExecutionId in headers for import run through SRM API for skipping events using jobExecutionId  from headers
