folio-org/mod-source-record-manager

ramls/metadata-provider.raml

Make request param "landingPage" optional

Make request param "landingPage" optional

---

src/main/java/org/folio/services/converters/JobExecutionToDtoConverter.java
src/main/resources/templates/db_scripts/schema.json
src/main/resources/templates/db_scripts/setup_test_data.sql
src/test/resources/org/folio/services/converters/jobExecutionCollectionMultipleTest.sample
src/test/resources/org/folio/services/converters/jobExecutionCollectionSingleTest.sample

MODSOURMAN-26. Stub test data to the release version.

MODSOURMAN-26. Stub test data to the release version.

---

src/main/java/org/folio/dao/JobExecutionDao.java
src/main/java/org/folio/dao/JobExecutionDaoImpl.java
src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/test/java/org/folio/TestUtil.java
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderLogAPITest.java
src/test/java/org/folio/services/converters/JobExecutionToDtoConverterUnitTest.java
src/test/java/org/folio/services/converters/JobExecutionToLogDtoConverterUnitTest.java
src/test/resources/org/folio/rest/files.sample

Modsourman-35 : Apply backend sorting for the Log entities
Modsourman-36 : Select only COMMITTED JobExecutions (Logs) on backend

Modsourman-35 Modsourman-36

---

ramls/metadata-provider.raml
src/main/java/org/folio/dao/JobExecutionDao.java
src/main/java/org/folio/dao/JobExecutionDaoImpl.java
src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/test/java/org/folio/TestUtil.java
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderLogAPITest.java
src/test/java/org/folio/services/converters/JobExecutionToDtoConverterUnitTest.java
src/test/java/org/folio/services/converters/JobExecutionToLogDtoConverterUnitTest.java
src/test/resources/org/folio/rest/files.sample

* JobExecutions filtered by status (COMMITTED and ERROR) to extract Logs
* Logs sorted by completedDate in descending order

MODSOURMAN-35 MODSOURMAN-36  Filter JobExecutions to extract Logs and apply sorting

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/change-manager.raml
ramls/metadata-provider.raml
src/main/java/org/folio/dao/JobExecutionDao.java
src/main/java/org/folio/dao/JobExecutionDaoImpl.java
src/main/java/org/folio/dao/util/DaoUtil.java
src/main/java/org/folio/dao/util/JobExecutionMutator.java
src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
src/main/java/org/folio/services/JobExecutionService.java
src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/main/java/org/folio/services/converters/Status.java
src/main/java/org/folio/util/RestUtil.java
src/test/java/org/folio/rest/impl/AbstractRestTest.java
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

* Created endpoint for getting JobExecution children by parent id
* Created endpoint for updating JobExecution status

MODSOURMAN-41

---

src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/main/java/org/folio/services/converters/JobExecutionToDtoConverter.java
src/main/java/org/folio/services/converters/JobExecutionToLogDtoConverter.java
src/main/resources/templates/db_scripts/setup_test_data.sql
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderLogAPITest.java
src/test/java/org/folio/services/converters/JobExecutionToDtoConverterUnitTest.java
src/test/java/org/folio/services/converters/JobExecutionToLogDtoConverterUnitTest.java
src/test/resources/org/folio/services/converters/jobExecutionCollectionMultipleTest.sample
src/test/resources/org/folio/services/converters/jobExecutionCollectionSingleTest.sample

Applied JobProfile entity
Updated unit and REST tests

Moddataimp 39 Apply JobProfile entity

---

src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/main/java/org/folio/services/converters/JobExecutionToDtoConverter.java
src/main/java/org/folio/services/converters/JobExecutionToLogDtoConverter.java
src/main/resources/templates/db_scripts/setup_test_data.sql
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderLogAPITest.java
src/test/java/org/folio/services/converters/JobExecutionToDtoConverterUnitTest.java
src/test/java/org/folio/services/converters/JobExecutionToLogDtoConverterUnitTest.java
src/test/resources/org/folio/services/converters/jobExecutionCollectionMultipleTest.sample
src/test/resources/org/folio/services/converters/jobExecutionCollectionSingleTest.sample

Rename "profile" field to "jobProfile" for proper class generation

Apply JobProfile entity

---

descriptors/ModuleDescriptor-template.json
ramls/change-manager.raml
src/main/java/org/folio/dao/FileExtensionDao.java
src/main/java/org/folio/dao/FileExtensionDaoImpl.java
src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
src/main/java/org/folio/services/FileExtensionService.java
src/main/java/org/folio/services/FileExtensionServiceImpl.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/AbstractRestTest.java
src/test/java/org/folio/rest/impl/changeManager/FileExtensionAPITest.java

* described endpoints in raml
* defined db table
* implemented FileExtension service and FileExtensionDao
* API covered with tests

MODSOURMAN-42 Created CRUD for File Extension management

---

descriptors/ModuleDescriptor-template.json
ramls/change-manager.raml
src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
src/main/java/org/folio/services/JobExecutionService.java
src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

* Added endpoint for setting JobProfile for JobExecution
* Simplified UPDATE JobExecution method
* Updated tests

MODSOURMAN-43 Add endpoint for setting JobProfile and Simplify logic of Update method for JobExecution

---

ramls/change-manager.raml
src/main/java/org/folio/dao/JobExecutionDao.java
src/main/java/org/folio/dao/JobExecutionDaoImpl.java
src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
src/main/java/org/folio/services/JobExecutionService.java
src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/test/java/org/folio/rest/impl/AbstractRestTest.java
src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

* GET children by parent id made searchable and pageable
* default limit value set to some big number

MODSOURMAN-48 Children JobExecution collection made searchable and pageable

---

src/main/resources/templates/db_scripts/setup_test_data.sql

Test data populates correctly on local deployment

MODSOURMAN-54 Set valid UUIDs in setup_test_data.sql script

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
src/main/java/org/folio/services/FileExtensionService.java
src/main/java/org/folio/services/FileExtensionServiceImpl.java
src/main/resources/templates/db_scripts/defaultFileExtensions.sql
src/test/java/org/folio/rest/impl/AbstractRestTest.java
src/test/java/org/folio/rest/impl/metadataProvider/FileExtensionAPITest.java

* Updated defaultFileExtensions
* Changed FileExtensionService, runtime request mod-users to get user information
* Fixed tests

MODSOURMAN-58 - Add support of full personal data for FileExtensions

---

NEWS.md
pom.xml
src/main/java/org/folio/config/ApplicationConfig.java
src/main/java/org/folio/dao/JobExecutionDao.java
src/main/java/org/folio/dao/JobExecutionDaoImpl.java
src/main/java/org/folio/dao/JobExecutionSourceChunkDao.java
src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java
src/main/java/org/folio/dao/util/PostgresClientFactory.java
src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
src/main/java/org/folio/rest/impl/InitAPIImpl.java
src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
src/main/java/org/folio/services/ChangeEngineServiceImpl.java
src/main/java/org/folio/services/ChunkProcessingServiceImpl.java
src/main/java/org/folio/services/JobExecutionService.java
src/main/java/org/folio/services/JobExecutionServiceImpl.java
src/main/java/org/folio/services/converters/JobExecutionToDtoConverter.java
src/main/java/org/folio/services/converters/JobExecutionToLogDtoConverter.java

Description
Change all services implementations to be @Service or @Component

MODSOURMAN-50 Add DI support to the module

---

src/main/java/org/folio/services/ChangeEngineService.java
src/main/java/org/folio/services/ChangeEngineServiceImpl.java
src/main/java/org/folio/services/ChunkProcessingServiceImpl.java

* Update counter of processed records in the chunk
* Update state of chunk to ERROR if processing failed

MODSOURMAN-70 Updated counter of processed records

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/converters/JobExecutionToDtoConverter.java
mod-source-record-manager-server/src/main/java/org/folio/services/converters/Status.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/converters/jobExecutionCollectionSingleTest.sample
ramls/change-manager.raml

* deleted IMPORT_IN_PROGRESS and IMPORT_FINISHED statuses
* added stub RunBy, Progress, startedDate fields for JobExecutions

MODSOURMAN-88 MODSOURMAN-89 Removed IMPORT_IN_PROGRESS and IMPORT_FINISHED statuses

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/setup_test_data.sql

Add stub data on backend for testing Job Profile page

MODSOURMAN-87 Add stub data on backend for testing Job Profile page

---

descriptors/ModuleDescriptor-template.json

Should depend upon inventory interface

MODSOURMAN-105

---

mod-source-record-manager-server/src/main/java/org/folio/services/AdditionalFieldsConfig.java
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceTest.java

- Created functionality to put record id into target field
- Tests are in place

Put SRS UUID into 999 field

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

Set COMMITTED status after the successful processing for jobExecution so it can be showed up in logs

MODSOURMAN-114

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/InstanceProcessingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

Using instance id from entity otherwise from response header

After Instances are created the field 999 appears without instance id

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDao.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java

Ensure COMMITTED status has been set for the loaded jobExecutions

MODSOURMAN-116

---

mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

MODSOURMAN-112 Implement a more elaborate way to define a RecordParser

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDao.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/ChunkProcessingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/services/MappingTest.java

Added criteria on JobExecutionSourceChunk.State.ERROR when checking if processing completed for all chunks

MODSOURMAN-138

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/InstanceProcessingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

- updated mod-source-record-storage-client

MODSOURCE-56 Partial batch update for parsed records

---

mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

test was fixed in scope of [MODSOURMAN-141](https://github.com/folio-org/mod-source-record-manager/pull/134/commits/e4b732daea6cae951dd9fe74c9ff33e907e284a0)

MODSOURMAN-143 - Fix at times not working test

---

mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/InstanceProcessingServiceImpl.java

MODDATAIMP-145

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json
ramls/instance.json

Update instance schema and mapping

Modsourman 149 - Update instance schema and mapping

---

mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

Corrected mapping rules to use default contributorNameTypeId

MODSOURMAN-149

---

mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

Corrected mapping rules to use default contributorNameTypeId

Modsourman 149 update mapping

---

NEWS.md
mod-source-record-manager-client/pom.xml
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/test/java/org/folio/services/MappingTest.java
pom.xml

Tmp release 1.5.0

---

mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

- Leave out any subfields that start with a number
- Include any subfields that start with letters

MODDATAIMP-181 - Subject headings

---

mod-source-record-manager-server/src/test/java/org/folio/services/MappingTest.java

Removed Ignore annotation of mapping test after release

Revert "Temporarily ignore mapping test"

---

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/Processor.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

*Classification (rows 17-22)*
Be sure to assign classification types for the various classification fields
* 050 & 090: LC
* 060: NLM
* 080: UDC
* 082: Dewey
* 086: GDC
LC, NLM, UDC (050, 090, 060, 080): 
* Put $a and $b in the same classification field, separated by a space
Dewey (082)
* Put $a (may be more than one) and $b in the same classification field, separated by a space
* If there is a slash in the $a, remove it and close up the space

Modsourman 173

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParameters.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParametersBuilder.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json
ramls/change-manager.raml
ramls/settings/contributornametype.json
ramls/settings/contributornametypes.json

Name type:
Personal name: in 100 or 700 field
Corporate name: in 110 or 710 field
Meeting name: in 111 or 711 field

MODSOURMAN-186 Added contributor name type settings loading for mapping

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/enums/ElectronicAccessRelationshipEnum.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParameters.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParametersBuilder.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json
ramls/change-manager.raml
ramls/settings/electronicaccessrelationship.json
ramls/settings/electronicaccessrelationships.json

Relationship: map from 856 2nd indicator; see values in mapping table rows 137-139. If none of these apply, assign “No information provided”
Resource | 2nd indicator 0
Version of Resource | 2nd indicator 1
Related resource | 2nd indicator 2

Modsourman 174

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

**Type,free text** is contributor field in $e (for 100/110/700/710) or $j (for 111/711);
- if $e/$j matches to Settings/Contributor types just put into **Type,free text** field.
- If no match - write it into **Type,free text** as it is;

Modsourman 171 contributor type text

---

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

ISBN
Comes from 020 $a $q $c all put together in whatever order they appear in the 020; $q may be repeated; remove the subfield mark and letter; add a space between subfields
Invalid ISBN 
Comes from 020 $z $q $c all put together in whatever order they appear in the 020; $q may be repeated; remove the subfield mark and letter; add a space between subfields

MODSOURMAN-170: setup isbn type id from settings

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

Review the subfields carefully to determine ISSN Identifier Type
022 $a = ISSN
022 $m $y $z = Invalid ISSN
022 $l = Linking ISSN

MODSOURMAN-170: set up ISSN type id from settings

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParameters.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParametersProvider.java
mod-source-record-manager-server/src/main/resources/rules.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json
ramls/change-manager.raml
ramls/settings/instancenotetype.json
ramls/settings/instancenotetypes.json

Note type name | field
-- | --
Cartographic Mathematical Data | 255$abcdefg
General note | 500$a35
With note | 501$a5
Dissertation note | 502$abcdgo
Bibliography note | 504$ab
Formatted Contents Note | 505$agrtu
Restrictions on Access note | 506$abcdefu235
Scale note for graphic material | 507$ab
Creation / Production Credits note | 508$a
Citation / References note | 510$abcux3
Participant or Performer note | 511$a
Type of report and period covered note | 513$ab
Data quality note | 514$abcdefghijkmuz
Numbering peculiarities note | 515$a
Type of computer file or data note | 516$a
Date / time and place of an event note | 518$adop23
Summary | 520$abcu23
Target Audience note | 521$ab3
Geographic Coverage note | 522$a
Preferred Citation of Described Materials note | 524$a23
Supplement note | …

MODSOURMAN-175 - Added note types settings loading for instance mapping

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderLogAPITest.java

requires adding "?query=cql.allRecords=1 sortBy completedDate/sort.descending" on getLogs for landing page

MODSOURMAN-212 Fixed sorting and filtering of logs

---

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/Processor.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

MODSOURMAN-177

---

mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

JIRA-ticket: https://issues.folio.org/browse/MODSOURMAN-255
1. If JobExecution failed - the value of the total records will be 0.
2. The test was updated.

MODSOURMAN-255: Logs show that failed to load files contain 100 records

---

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/resources/rules/rules.json
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json

MODSOURCE-108 - Define rules for instance identifier types without hardcoded types UUIDs

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java

In scope of task MODSOURCE-107 I Changed the place of setting generation value and make some changes to test class for covering my added functionallity.

MODSOURCE-107 Changed the place of set generation value

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunction.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/NormalizationFunctionRunner.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/functions/enums/IssuanceModeEnum.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParameters.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/parameters/MappingParametersProvider.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/services/MappingTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/mapping/functions/NormalizationFunctionTest.java
ramls/change-manager.raml
ramls/settings/issuancemode.json
ramls/settings/issuancemodes.json

1. New mechanism for mapping "mode of issuance" was created.
2. Mode of issuance entity was created.

MODSOURMAN-203: Map Mode of issuance

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java
ramls/change-manager.raml

In scope of story MODSOURMAN-260 I added query param defaultMapping and condition for choosing a service depending on query param value.

MODSOURMAN-260 Added query param and condition for choosing a service

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/test/resources/org/folio/services/mapping/instances.json
mod-source-record-manager-server/src/test/resources/schema/instance.json
ramls/instance.json

In scope of story MODDICONV-103 I updated schemas in raml-storage and versions of some dependencies and added new fields in instance.json.

MODDICONV-103 Updated schemas in raml-storage

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerHandlersImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/EventDrivenChunkProcessingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/RecordProcessedEventHandlingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/EventHandlersApiTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java

1. Mechanism for zipping/unzipping added.

MODSOURMAN-300: Archive event payload

---

mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerHandlersImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/RecordProcessedEventHandlingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/util/EventHandlingUtil.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/EventHandlersApiTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java

1. Zipping and unzipping event payload added to specific places.
2. Tests added.

MODSOURMAN-305: Apply archive/unarchive eventPayload mechanism

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/services/JobExecutionProgressServiceImplTest.java

1. New constraint on  unique "jobexecutionId" field added.
2. Test added.

MODSOURMAN-311: JobExecution duplicates for Cornell file  [BUGFIX]

---

NEWS.md
mod-source-record-manager-server/src/main/resources/rules/rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/rules.json

Update mapping for Preceding/Succeeding Titles

MODDICORE-41 Update mapping for Preceding/Succeeding Titles

---

descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/InstanceProcessingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerParsedRecordsAPITest.java

[MODSOURMAN-325](https://issues.folio.org/browse/MODSOURMAN-325)
This PR will be merged after SRS refactoring-master branch is merged to master. 
Dependency to SRS v4.0.0 will be updated after all the changes are verified on the envs and SRS module is released.

MODSOURMAN-325 Update SRS client requests for v4

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java

1. Name to jobProfileInfo was added as "CLI job profile".
2. NEWS updated.

MODSOURMAN-324: Hardcode JobProfile for importing records using CLI tool.

---

.rancher-pipeline.yml

initialization for .rancher-pipeline.yml

initialization for .rancher-pipeline.yml

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/HrIdFieldServiceImpl.java

003 handling in SRS for MARC Bib records: Create

MODSOURMAN-345

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

1. Script for adding column "title" added to the "journal_records" table.

MODSOURMAN-380: Expand journalRecord entity with "title" property.

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java
mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

1. Additional check for Status=COMMITED added. It will resolve an issue regarding stucking job on 100% when running data-import via CLI.

MODSOURMAN-385: Enable OCLC update processing.

---

PULL_REQUEST_TEMPLATE.md

https://issues.folio.org/browse/MODDATAIMP-360
Adding default PR template such as what has been used in other FOLIO repos  https://github.com/folio-org/mod-kb-ebsco-java/blob/master/PULL_REQUEST_TEMPLATE.md
- added default template

MODDATAIMP-360: Add PR template

---

mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java

ConsumersVerticle start and stop futures complete multiple times
Use Composite future

Fix multiple completion of the same future

---

descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/config/ApplicationConfig.java
mod-source-record-manager-server/src/main/java/org/folio/services/util/EventHandlingUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java

Set correct env variables names for kafka config

Fix kafka config

---

README.md
RuleProcessorApi.md

Steps from README doc for importing record through API missed a request for setting JobProfile for JobExecution
Documentation was updated and missing step was added

MODSOURMAN-413 Update documentation

---

mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java

to publish EDIFACT record for further processing
infer the corresponding context property by record type

MODINVOICE-231 - Fix EDIFACT record publishing

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/journal/InvoiceUtil.java
mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportJournalKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/EventTypeHandlerSelector.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/InvoiceImportEventHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/SpecificEventHandler.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleMockTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/EventTypeHandlerSelectorTest.java

Expand data import log functionality for EDIFACT records.
DataImportJournalConsumersVerticle was updated for receiving DI_INVOICE_CREATED events.

MODSOURMAN-410: Expand data import log functionality for EDIFACT records. Part 1: Save info into DB.

---

NEWS.md
mod-source-record-manager-client/pom.xml
mod-source-record-manager-server/pom.xml
pom.xml

Release 3.0.0

---

NEWS.md
mod-source-record-manager-server/src/main/resources/rules/rules.json

[MODSOURMAN-421](https://issues.folio.org/browse/MODSOURMAN-421)
syntax adjustment

MODSOURMAN-421 - Adjusted mapping rule for 561 field

---

mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/journal/InvoiceUtil.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleMockTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/ImportInvoiceJournalConsumerVerticleTest.java

Expand data import log functionality for EDIFACT records
The function get_job_log_entries was updatet to include invoice line information.

MODSOURMAN-410: Expand data import log functionality for EDIFACT records (Improve SQL for main Logs screen)

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql

Incorrect number of data returned
Exclude EDIFACT type from SQL request

Fix SQL: exclude EDIFACT type from request

---

mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/JournalRecordsColumns.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql

Incorrect order for the mark and edifact records
Change logic for receiving data from SQL

Fix the record order issue for the mark and edifact records.

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql

Returns format for function get_job_log_entries was changed.
New request to delete previous version on this function.

Request to delete the old version of get_job_log_entries with a different return format.

---

mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordServiceImpl.java

Instances in Inventory are not updated with the appropriate user name when the source record is updated via QM
Update QM-event with user context that contains user ID and okapi token.
Required changes in mod-inventory: https://github.com/folio-org/mod-inventory/pull/329

MODSOURMAN-441 Update QM-event with user context

---

NEWS.md
mod-source-record-manager-server/src/main/resources/rules/rules.json

update mapping rule for 647 field 
[MODSOURMAN-448](https://issues.folio.org/browse/MODSOURMAN-448)

MODSOURMAN-448 - Default field mapping for 647 field needs updating

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandlerTest.java

to correctly provide records creation info for the log summary page in case of error while saving records in the record-storage
* move logging of the records creation information to the handler receiving saved records
* tests
[MODSOURCE-278](https://issues.folio.org/browse/MODSOURCE-278)

MODSOURCE-278 - Record from chunk is not saved occasionally

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json

Due to changes made in scope of https://issues.folio.org/browse/MODSOURMAN-477 interfaces version should be updated to notify dependant modules about changes. 
* updated provided interface version for "source-manager-job-executions", "source-manager-records" from 1.1 to 2.0
* updated requires interface version for "source-storage-source-records", "source-storage-records" from 2.0 to 3.0
* updated README.md file

MODSOURMAN-485 - Update interface version

---

README.md
descriptors/ModuleDescriptor-template.json

Revert "MODSOURMAN-485 - Update interface version (#436)"

---

mod-source-record-manager-server/pom.xml

MODDPUBSUB-181: Update folio-kafka-wrapper version to 2.4.0-SNAPSHOT

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/AbstractRestTest.java

MODPUBSUB-181: Bump folio-kafka-wrapper version to 2.3.1

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/progress/JobExecutionProgressServiceImpl.java

The purpose is to merge the MODDATATIMP-475 into the Juniper branch

MODSOURMAN-513 v3.1.0

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java

to import EDIFACT invoice and recognize record type appropriately
* fix record type determination
* add test
[MODSOURMAN-527](https://issues.folio.org/browse/MODSOURMAN-527)

MODSOURMAN-527 - Cannot import EDIFACT invoices

---

NEWS.md
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/AdditionalFieldsUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/afterprocessing/AdditionalFieldsUtilTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/JobMonitoringWatchdogVerticleTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleTest.java

Support MARC Holdings
* extend JournalParams
* extend EngineService with 004 field validation
* add tests

MODSOURMAN-524 Support MARC Holdings

---

mod-source-record-manager-server/src/main/java/org/folio/dao/MappingParamsSnapshotDaoImpl.java

Save mapping params snapshot as json object instead of escaped string

MODDATAIMP-544 - Save mapping params snapshot as json object 

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

Fix rule_type enum creation for several tenants

MODSOURMAN-574 Fix rule_type enum creation

---

NEWS.md
RuleProcessorApi.md
mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json

In scope of the task added new rules;
- Updated rules for 024 field
https://issues.folio.org/browse/MODDICORE-172

MODDICORE-172 Add MARC-Instance field mapping for New identifier types

---

descriptors/ModuleDescriptor-template.json

Add required permissions for QM edit flow
Add permissiosn to update holdings via quickMarc for '/change-manager/parsedRecords/{id}':
* inventory-storage.holdings.item.get
* inventory-storage.holdings.item.put

MODSOURMAN-578 Add required permissions for QM edit flow

---

descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/DataImportPayloadContextBuilderImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java
mod-source-record-manager-server/src/test/java/org/folio/services/DataImportPayloadContextBuilderImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java

 For importing MARC Authority we should:
* remove mock in the eventPayload.
* update ChangeEngineServiceImpl by adding MARC_AUTHORITY in the method ensureMappingMetaDataSnapshot
* add a new event to JournalParams to map Inventory Authority, write test case
* add required permissions to module descriptor
* Remove STUB in the RecordsPublishingServiceImpl#prepareEventPayload 
* Remove verification in the DataImportPayloadContextBuilderImpl#createAndPopulateContext
[MODSOURMAN-602](https://issues.folio.org/browse/MODSOURMAN-602)

MODSOURMAN-602: Remove STUB for MARC Authority in Event Payload

---

NEWS.md
README.md
mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json

MODSOURMAN-605 Authority: update rules for name-title fields/properties

---

NEWS.md
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java

Generate a 999 ff $i
Generate ID in ChangeEngineService and put it into MARC record

MODSOURMAN-623-generate-authority-id

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/JournalRecordsColumns.java
mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

MODSOURMAN-619 Add an Authority info for Import Log for record page

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/MappingRuleServiceImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/dao/MappingRuleDaoImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/MappingRuleServiceTest.java

Fix saving of default mapping rules
Do not override mapping rules if they are already exist in database

MODSOURMAN-621 Fix saving of default mapping rules

---

mod-source-record-manager-server/src/main/java/org/folio/services/util/ParsedRecordUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java

Populate Authority Journal record with title from 1XX tag
Extend MarcImportEventsHandler with logic of extraction title for MARC Authority

MODSOURMAN-626 Populate Authority Journal record with title

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportKafkaHandler.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportKafkaHandlerMockTest.java

NPE via data-import using "Holding-content"-file but with MARC-Bib holdings creation.
Added "recordId" and some checks to avoid NPE.
JIRA: https://issues.folio.org/browse/MODSOURMAN-643

MODSOURMAN-643: Fix NPE exception and fix the main reason of NPE (recordId = null)

---

mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java

Fix Authority journal
Make DataImportJournalConsumersVerticle listen DI_SRS_MARC_AUTHORITY_RECORD_CREATED event

MODSOURMAN-626 Fix Authority journal

---

mod-source-record-manager-server/pom.xml
pom.xml

v33.2.1 contains log4j vulnerability fix

Upgrade to RMB 33.2.1

---

mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json

Populate subjectHeadings with the right value for MARC authority
Fix correct population of 11 position
https://issues.folio.org/browse/MODSOURMAN-655

MODSOURMAN-655 Populate subjectHeadings with the right value

---

NEWS.md
README.md
mod-source-record-manager-server/src/main/java/org/folio/config/ApplicationConfig.java

To remove all Kafka cache occurrences
https://issues.folio.org/browse/MODDATAIMP-623

MODDATAIMP-623 Remove Kafka cache initialization and Maven dependency

---

mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java

Fix IllegalArgumentException in SRS when receive DI_INVENTORY_INSTANCE_CREATED_READY_FOR_POST_PROCESSING event
- Added new event type tp journal param
https://issues.folio.org/browse/MODSOURCE-417

MODSOURCE-417 Added new forgotten journal param

---

mod-source-record-manager-server/src/main/java/org/folio/services/entity/MappingRuleCacheKey.java

We need display changes in search result, after edit authority record
Initialization rule cache key for MARC authorities
[MODSOURMAN-683](https://issues.folio.org/browse/MODSOURMAN-683)

MODSOURMAN-683 Updating a MARC tag does not return in search results

---

mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandler.java

Prevent huge stack traces for DuplicateEventException in RawMarcChunksKafkaHandler like this:
```
11:01:04.718 [vert.x-worker-thread-14] ERROR rcChunksKafkaHandler [667698eqId] RawRecordsDto processing has failed with errors chunkId: ccfcec6f-ec09-4415-b208-9d5378c443fc chunkNumber: 23 - org.folio.rest.jaxrs.model.RecordsMetadata@643da776 for jobExecutionId: 1d95c4fb-e02f-4ecf-a5be-3fa08279951d 
org.folio.kafka.exception.DuplicateEventException: Source chunk with 0cae57bc-35c2-42f0-8d2c-055a1012d721 id for 1d95c4fb-e02f-4ecf-a5be-3fa08279951d jobExecution is already exists 
at org.folio.services.AbstractChunkProcessingService.lambda$processChunk$1(AbstractChunkProcessingService.java:53) ~[mod-source-record-manager-server-fat.jar:?] 
at …
```

MODDATAIMP-633. Improve logging to not log stack traces for DuplicateEventException

---

NEWS.md
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/dao/JobMonitoringDaoImpl.java
pom.xml

to pick up vertx fix for SimpleConnectionPool and prevent timeout issues during awaiting connection on the pg-pool
* upgrade vertx to v4.2.4
* upgrade rmb to v33.2.5
* upgrade folio-di-support to v1.4.1
[MODSOURMAN-706](https://issues.folio.org/browse/MODSOURMAN-706)

MODSOURMAN-706 - Error loading MappingParametersSnapshot

---

pom.xml

Upgrade RMB and Vertx versions that contain fixes for the connection pool
https://issues.folio.org/browse/MODSOURMAN-711

Upgrade RMB to 33.2.6 and Vertx to 4.2.5

---

descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionFilter.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/dao/JobExecutionDaoImplUnitTest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

Suppress the logs produced by MARC Authority Delete actions from the Data Import logs UI.
* Extend JobProfileInfo with new field
* Update job_execution table with new field "job_profile_hidden" with type boolean default value = "false"
* Add changes to mapping dto to row and row to dto in JobExecutionDao
* Add changes to JobExecutionFilter.buildCriteria() method to return criteria with "job_profile_hidden = false"
* Update tests and add new for JobExecutionDao
* Update tests and add new for MetadataProviderImpl

MODSOURMAN-707 Add field `hidden` to filter jobs

---

mod-source-record-manager-server/pom.xml

Update mod-data-import-converter-storage-client

MODSOURMAN-707 Update mod-data-import-converter-storage-client

---

descriptors/ModuleDescriptor-template.json
pom.xml

Upgrade RMB and new parameters: DB_RECONNECTATTEMPTS and DB_RECONNECTINTERVAL
DB_RECONNECTATTEMPTS and DB_RECONNECTINTERVAL was added to module-descriptor
https://issues.folio.org/browse/MODSOURMAN-712

MODSOURMAN-712: Upgrade RMB and new parameters: DB_RECONNECTATTEMPTS and DB_RECONNECTINTERVAL

---

NEWS.md
mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json

Fix mapping for Authority 010 tag

MODSOURMAN-727 Fix mapping for Authority 010 tag

---

mod-source-record-manager-server/src/main/java/org/folio/dao/MappingRuleDaoImpl.java

Failed to restore Authority mapping rules.
Exception on DAO level:
io.vertx.pgclient.PgException: ERROR: syntax error at or near "s" (42601)
Use prepared statement

MODSOURMAN-752 Fix PgException while restore mapping rules

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/QuickMarcUpdateKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/QuickMarcUpdateKafkaHandlerTest.java

Fix state is "In progress" after successful quickMarc update

MODSOURMAN-767 Fix state is "In progress" after successful quickMarc update

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDao.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java
mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionService.java
mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
ramls/change-manager.raml

This is a new API being introduced to delete single or multiple data-import logs
Calling this API will allow deleting one or more data-import logs depending upon the information sent.

MODSOURMAN-771 - New API information for DI Delete Logs

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

Delete deprecated table. All data was migrated to job_execution table.
[MODSOURMAN-808](https://issues.folio.org/browse/MODSOURMAN-808)
[MODSOURMAN-468](https://issues.folio.org/browse/MODSOURMAN-468)

MODSOURMAN-808 Drop deprecated job_execution(s!) table

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java

- Add userId to kafkaHeaders
- Optimize imports
https://issues.folio.org/browse/MODSOURMAN-809

MODSOURMAN-809 Add userId to kafkaHeaders for DI_RAW_RECORDS_CHUNK_PARSED event

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDao.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/JournalRecordService.java
mod-source-record-manager-server/src/main/java/org/folio/services/JournalRecordServiceImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java
ramls/metadata-provider.raml

Create ability to fetch job log entries filtering by entity type using new implemented param.
[MODSOURMAN-810](https://issues.folio.org/browse/MODSOURMAN-810)

MODSOURMAN-810 Improve summary endpoint by parameter "entityType"

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JournalParams.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/JournalParamsTest.java

Support MARC-MARC Holdings update action
JIRA: https://issues.folio.org/browse/MODSOURMAN-815
- Extend ChangeEngineServiceImpl to be able to send DI_MARC_FOR_UPDATE_RECEIVED event if update Marc Holdings - action exists in job profile
- Extend JournalParams with new events
- Update tests

MODSOURMAN-815 Support MARC-MARC Holdings update action

---

descriptors/ModuleDescriptor-template.json

Required by https://issues.folio.org/browse/MODUSERS-212

MODSOURMAN-832 Add support for users interface v16.0

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/update_source_chunks_table_structure_if_needed.sql

Fix error while upgrading srm.
Added fixes to avoid errors if there are already added triggers/functions.
JIRA: https://issues.folio.org/browse/MODSOURMAN-870

MODSOURMAN-870: Error while updating module after fix for schema differences between MG Bugfest and clean MG deployment

---

mod-source-record-manager-server/pom.xml

Bumping test-container version as in the release version.

TestContainer version bumped.

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

Make installation and migration idempotent so that a sysop can run it multiple times.

MODSOURMAN-885: column jep1.jobexecutionid does not exist

---

mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionSourceChunkDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobMonitoringDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/MappingParamsSnapshotDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/MappingRuleDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/MappingRulesSnapshotDaoImpl.java
pom.xml

Upgrade to RMB v35.0.0
[MODSOURMAN-883](https://issues.folio.org/browse/MODSOURMAN-883)

[MODSOURMAN-883] Upgrade to RMB v35.0.0

---

mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

Fixed sorting in the Status column
Jira: https://issues.folio.org/browse/MODSOURMAN-887

[MODSOURMAN-887] Fixed sorting in the Status column

---

mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java

Fix sorting in Records column
Jira: https://issues.folio.org/browse/MODSOURMAN-822

[MODSOURMAN-822] Fixed sorting in Records column

---

NEWS.md
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json

to map MARC 720 field to instance contributor
* add marc-bib mapping rule for 720 field
[MODSOURMAN-873](https://issues.folio.org/browse/MODSOURMAN-873)

MODSOURMAN-873 - Add MARC 720 field to default MARC Bib-Instance mapping and adjust relator term mapping

---

PULL_REQUEST_TEMPLATE.md
mod-source-record-manager-server/src/main/resources/log4j2.properties
mod-source-record-manager-server/src/test/resources/log4j2-test.properties

Logging improvement - Configuration
Jira: https://issues.folio.org/browse/MODSOURMAN-892

[MODSOURMAN-892] Logging improvement - Configuration

---

mod-source-record-manager-server/pom.xml

Test folio-kafka-wrapper-util logging improvement

[KAFKAWRAP-21] Test folio-kafka-wrapper-util logging improvement

---

mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/main/resources/templates/db_scripts/update_set_file_name_from_null_to_no_file_name.sql

https://issues.folio.org/browse/MODSOURMAN-894

[MODSOURMAN-894]Logs for "No file name" sort at the end of the file name alpha list instead of in the N's

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

to update module version for the scripts

MODSOURMAN-819 - The status of Instance is Multiple in the Import log after uploading MARC file for update

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

No log hotlink for Holdings and/or Item when job has no action on Instance
Changed migration scripts and added new tests

[MODSOURMAN-911] No log hotlink for Holdings and/or Item 

---

mod-source-record-manager-server/src/main/resources/log4j2-json.properties
mod-source-record-manager-server/src/test/resources/log4j2-test.properties

Adjust logging configuration to display datetime in a proper format
Display date
Configured Pattern
Jira: https://issues.folio.org/browse/MODDATAIMP-736

[MODDATAIMP-736] Adjust logging configuration to display datetime in a proper format

---

descriptors/ModuleDescriptor-template.json

to provide permissions for order creation
[MODORDERS-773](https://issues.folio.org/browse/MODORDERS-773)

MODORDERS-773 - Added permissions for order creation

---

mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json

Add authority ID to alternativeTitles mapping rules

MODSOURMAN-924 Add authority ID to alternativeTitles mapping rules

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/JournalRecordsColumns.java
mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

The main goal is to add new field "order_id" to the "journal_records"-table.
Extended schema and codebase where needed.
(https://issues.folio.org/browse/MODSOURMAN-948)

MODSOURMAN-948: Improve schema for the 'journal_records'-table to be able to import Orders

---

descriptors/ModuleDescriptor-template.json

Update endpoints:
POST /change-manager/jobExecutions/{id}/records
PUT /change-manager/parsedRecords/{id}
with module permissions:
instance-authority-links.instances.collection.get
instance-authority-links.instances.collection.put

MODSOURMAN-949 Update permissions for links update

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql

Prevent 500 error while schema upgrade
Added DROP for get_job_execution_summary function and updated DROP for get_job_log_entries function

[MODSOURMAN-932] Updated migrations scripts

---

mod-source-record-manager-server/pom.xml
pom.xml

Update util dependencies
Updated dependencies and updated util dependencies to SNAPSHOT versions

[MODDATAIMP-750] Update util dependencies

---

mod-source-record-manager-client/pom.xml
mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/ParsedRecordServiceImpl.java

Set SNAPSHOT version for modules' client dependencies
Bumped clients' versions, updated di-conv dependency to reference to renamed one, updated method parameters to fit updated srm client interface

[MODDATAIMP-750] Set SNAPSHOT version for modules' client dependencies

---

mod-source-record-manager-server/src/test/resources/org/folio/services/marc_mapping_params.json

Add new organizations field to tests
Fix test failures due to adding new field to MappingParams in di-core

[MODORDERS-844] Add new organizations field to tests

---

mod-source-record-manager-server/pom.xml

Update mod-di-converter-storage-client and data-import-processing-core dependencies
Updated dependencies

[MODDICORE-306] Update mod-di-converter-storage-client and data-import-processing-core dependencies

---

mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json

Fix unexpected property in marc-authority mapping rules

MODSOURMAN-931 Fix unexpected property in marc-authority mapping rules

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

Enable logs for MATCH action
Remove condition on MATCH action

[MODSOURCE-610] Enable logs for MATCH action

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

When action on entity performed in non_match section job summary count it as "Discarded"
Check for other actions while counting Discarded

[MODSOURMAN-835] Show Discarded in summary when NON_MATCH and no other action

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/rest/impl/ChangeManagerImpl.java
mod-source-record-manager-server/src/main/java/org/folio/rest/impl/MetadataProviderImpl.java
mod-source-record-manager-server/src/test/resources/org/folio/services/marc_mapping_params.json
ramls/change-manager.raml
ramls/mapping-metadata-provider.raml
ramls/mapping-rules-provider.raml
ramls/metadata-provider.raml

MODSOURMAN-984 Update action profile schema

---

mod-source-record-manager-server/src/main/java/org/folio/services/afterprocessing/FieldModificationServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java
mod-source-record-manager-server/src/test/java/org/folio/services/FieldModificationServiceTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/mappers/processor/MappingParametersProviderTest.java

Fix subfield $9 removal
Fix mod-entities-links response parsing
[MODSOURMAN-974](https://issues.folio.org/browse/MODSOURMAN-974)

MODSOURMAN-974 MARC bib $9 handling | Remove $9 subfields from linkable fields

---

descriptors/ModuleDescriptor-template.json

to provide necessary module permissions (lack was spotted in karate tests)
https://issues.folio.org/browse/FAT-5839

FAT-5839 - Provided module permissions for GET /mapping-metadata/type/{recordType}

---

descriptors/ModuleDescriptor-template.json

to add dependencies on interfaces whose endpoints are needed for mapping parameters construction (lack of some was spotted during karate tests).
[FAT-5839](https://issues.folio.org/browse/FAT-5839)

FAT-5839 - Provided dependencies on interfaces whose endpoints are needed for mapping parameters construction

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/dao/EventProcessedDao.java
mod-source-record-manager-server/src/main/java/org/folio/dao/EventProcessedDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/PostgresClientFactory.java
mod-source-record-manager-server/src/main/java/org/folio/services/EventProcessedService.java
mod-source-record-manager-server/src/main/java/org/folio/services/EventProcessedServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/flowcontrol/RawRecordsFlowControlServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/AbstractConsumersVerticle.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportKafkaHandler.java
mod-source-record-manager-server/src/main/resources/log4j2-json.properties
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/main/resources/vertx-default-jul-logging.properties
mod-source-record-manager-server/src/test/java/org/folio/dao/EventProcessedDaoTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/EventProcessedServiceTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/RawRecordsFlowControlServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportKafkaHandlerMockTest.java

Previous Flow Control implementation heavily loaded the DB for module synchronization. 
Using a fetch(long) operator for managing to receive packages from DI_RAW_RECORDS_CHUNK_READ topic.
[MODSOURMAN-989](https://issues.folio.org/browse/MODSOURMAN-989)

Modsourman 989

---

mod-source-record-manager-server/pom.xml

_Upgrade `aspectj-maven-plugin` to Java 17 wIthin the scope of the whole module migration._
_`groupId` of `aspectj-maven-plugin` is migrated from `com.nickwongdev` to `dev.aspectj`_

MODSOURMAN-999: Upgrade aspectj-maven-plugin to Java 17

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java

Fix authority import logs after merging multiples
Set entity id for Authority
https://issues.folio.org/browse/MODSOURMAN-1027

[MODSOURMAN-1027] Fix authority import logs

---

mod-source-record-manager-server/pom.xml

The main purpose it to update link on the raml-storage to provide all needed schemas for Wrappers-feature.
JIRA: https://issues.folio.org/browse/MODDICONV-310

MODDICONV-310: Wrappers feature.

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java

Remove assigning of macthedId and generation to record to perform this logic at srs
Removed assigning of macthedId and generation

[MODSOURCE-530] Remove assigning of macthedId and generation to record

---

mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/util/JobExecutionDBConstants.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/alter_job_executions_table_for_total_records.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json

MODDATAIMP-911 add the totalRecordsInFile field to the Entity and DTO to support correct progress bar in UI-data-import application.

MODDATAIMP-911 add the totalRecordsInFile field to the Entity and DTO

---

mod-source-record-manager-server/pom.xml

Update inventory settings schemas that come from data-import-processing-core

Update di-processing-core dependency

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/IncomingRecordDao.java
mod-source-record-manager-server/src/main/java/org/folio/dao/IncomingRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/IncomingRecordService.java
mod-source-record-manager-server/src/main/java/org/folio/services/IncomingRecordServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/JournalRecordService.java
mod-source-record-manager-server/src/main/java/org/folio/services/JournalRecordServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_incoming_records_table.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/dao/IncomingRecordDaoImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/EventDrivenChunkProcessingServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/IncomingRecordServiceImplUnitTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java
ramls/change-manager.raml

Save DI logs as IncomingRecords in a new table
Save to DB IncomingRecords with JournalRecords after incoming records are parsed
Debugged locally

MODSOURMAN-1020: Save incoming records for DI logs

---

mod-source-record-manager-server/pom.xml

Inventory Single item imports and updates no longer supercede long-running data import jobs
Described in [KAFKAWRAP-50](https://github.com/folio-org/folio-kafka-wrapper/pull/48)

8MODINV-925: For testing changes related to flow control

---

mod-source-record-manager-server/src/main/java/org/folio/dao/JobExecutionFilter.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

Search by fileName should be case-insensitive
Use operator ILIKE for search by filename

[MODSOURMAN-996] Allow to search job executions by file name case-insensitive

---

mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportInitKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/DataImportJournalKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java
mod-source-record-manager-server/src/test/java/org/folio/services/mappers/processor/MappingParametersProviderTest.java

to prevent import job hanging when response schema mismatches

Fixed handling of response deserialization error

---

descriptors/ModuleDescriptor-template.json

Accomodate for authority-source-files api optimistic locking changes
Increase interface version

MODSOURMAN-1116 Accomodate for authority-source-files api optimistic locking changes

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

MODSOURMAN-1106: Fixed error counter and blank title record
Added default label if label is blank
Fixed error counter issue
Added sufficient amount of test cases related to job execution summary

MODSOURMAN-1106: Fixed error counter and blank title record

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/StoredRecordChunksKafkaHandler.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/StoredRecordChunkConsumersVerticleTest.java

Fix stuck of Orders creation
Add Order creation handling when create Order action received
Tested locally

MODDATAIMP-957: add Orders creation

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java

hot-fix: Add error message to Marc bib

hot-fix: Add error message to Marc bib

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql

Return job log entries for purchase orders
include the PO_LINE entity type in the list of expected entity types

FAT-9178 return job log entries for purchase order lines

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalConsumersVerticle.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java

When DI_INVENTORY_INSTANCE_UPDATED event received payload will contain MARC_BIB and Instance data and the flag to indicate action on MARC_BIB in the context.
[MODSOURMAN-1084](https://issues.folio.org/browse/MODSOURMAN-1084)

MODSOURMAN-1084: Fill in Journal Records for updated MARC when INSTANCE_UPDATED event received

---

mod-source-record-manager-server/src/main/java/org/folio/services/kafka/support/SRMKafkaTopic.java
mod-source-record-manager-server/src/test/java/org/folio/services/KafkaAdminClientServiceTest.java

add def namespace for topic names

add def namespace for topic names

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Provide "orders-storage.titles.item.get" module permission [MODDATAIMP-1003](https://folio-org.atlassian.net/browse/MODDATAIMP-1003)
* add permission into module permissions

MODDATAIMP-1003 Provide "orders-storage.titles.item.get" module permission

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/changeManager/ChangeManagerAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java

The import of file for creating orders is completed with errors [MODSOURMAN-1131](https://folio-org.atlassian.net/browse/MODSOURMAN-1131)
parse title from po line, update news

MODSOURMAN-1131 The import of file for creating orders is completed with errors

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java

The 'Item' status is '-' after importing file for updating
Adjust SQL condition to include DISCARDED items in job logs
[MODSOURMAN-1133](https://folio-org.atlassian.net/browse/MODSOURMAN-1133)

MODSOURMAN-1133 Adjust SQL condition to include DISCARDED items

---

mod-source-record-manager-server/src/main/java/org/folio/services/DataImportPayloadContextBuilderImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
mod-source-record-manager-server/src/test/java/org/folio/services/DataImportPayloadContextBuilderImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/util/MarcImportEventsHandlerTest.java

Set incoming record id at source_id
Set incoming record id to payload context and populate source id during journal record creation

[MODSOURMAN-1141] Set incoming record id at source_id

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/MarcImportEventsHandler.java
mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/DataImportJournalConsumerVerticleMockTest.java

Refactor source_id to be set during the build of journal records
Refactor source_id to be set during the build of journal records

[MODSOURMAN-1141] Refactor source_id to be set during the build of journal records

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

When holding the status is `UPDATED`, it is displayed as a dash (-).
Fix holdings CTE in get_job_entries_function

MODINV-968 Fix get_job_entries to return UPDATED holdings

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java

Marc authority records with errors are not displayed in the result table in the logs
Get incomingRecordId from record if recordId form event payload is null

MODSOURMAN-1146 Fix not displayed records with no action status

---

mod-source-record-manager-client/pom.xml
mod-source-record-manager-server/pom.xml
pom.xml

Upgrade mod-source-record-manager to RMB 35.2.0 and Vertx 4.5.4
[MODDICORE-398](https://folio-org.atlassian.net/browse/MODDICORE-398)

MODDICORE-398: Upgrade mod-source-record-manager to RMB 35.2.0 and Vertx 4.5.4

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/AbstractChunkProcessingService.java
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/InvalidJobProfileForFileException.java
mod-source-record-manager-server/src/main/java/org/folio/services/exceptions/InvalidJobProfileForFileException.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/JobExecutionUtils.java
mod-source-record-manager-server/src/test/java/org/folio/services/validation/JobProfileSnapshotValidationServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunksKafkaHandlerTest.java

Stop processing the job with incorrect profile
Added logic to stop following chunks when job profile is not compatible with file
[MODSOURMAN-956](https://folio-org.atlassian.net/browse/MODSOURMAN-956)

MODSOURMAN-956: Stop processing the job with incorrect profile

---

mod-source-record-manager-server/pom.xml

Updated the versions for three dependencies - folio-di-support, folio-kafka-wrapper, and data-import-processing-core - in the pom.xml file.

Updated the versions for three dependencies - folio-di-support, folio-kafka-wrapper, and data-import-processing-core

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/dao/JournalRecordDaoImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

Add incomingRecordId field at /metadata-provider/jobLogEntries/{jobExecutionId}/records/{recordId}
Added incoming record id column to processing log
[MODSOURMAN-1150](https://folio-org.atlassian.net/browse/MODSOURMAN-1150)

MODSOURMAN-1150: Add incomingRecordId field at /metadata-provider/jobLogEntries/{jobExecutionId}/records/{recordId}

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/exceptions/InvalidJobProfileForFileException.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/errorhandlers/RawMarcChunksErrorHandler.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/consumers/util/DiErrorBuilderUtil.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java

to display error message on the page with jsons if selected job profile is incompatible with the records
* populated error payload in case of incompatible job profile has been chosen
* update tests
[MODSOURMAN-1152](https://issues.folio.org/browse/MODSOURMAN-1152)

MODSOURMAN-1152 - The error message is not displayed in the di log summary

---

mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java

Save PARSE journal_record for MARC_HOLDINGS with invalid 004 field
Move sending DI_ERROR for parsed record with invalid 004 after saving PARSE journal_record

[MODSOURMAN-1170] Save PARSE journal_record for MARC_HOLDINGS with invalid 004 field

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java

Set entity_id for MARC_HOLDINGS and MARC_AUTHORITY records during Update
Extend if clause to set entity if for MARC_AUTHORITY and MARC_HOLDINGS

[MODSOURMAN-1177] Set entity_id for MARC_HOLDINGS and MARC_AUTHORITY records during Update

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/ChangeEngineServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/services/RecordsPublishingServiceImpl.java
mod-source-record-manager-server/src/test/java/org/folio/services/ChangeEngineServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/consumers/RawMarcChunkConsumersVerticleTest.java

to provide a corresponding error message for DI job logs in case of chosen job profile snapshot does not contain any child wrappers
* added validation for child wrappers existence
* added test
[MODSOURMAN-1173](https://issues.folio.org/browse/MODSOURMAN-1173)

MODSOURMAN-1173 - Handle Situation When Job Profile Has No Child Profiles

---

mod-source-record-manager-server/pom.xml
mod-source-record-manager-server/src/main/java/org/folio/services/mappers/processor/MappingParametersProvider.java

Timeout for requests increased to 30 seconds.
Updated version of data-import-utils

MODDATAIMP-1048: Increased timeout for requests.

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_execution_summary_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetadataProviderJobExecutionAPITest.java

Modify action before match breaks non match logs
Removed Modify action type from prioritization
[MODOSOURMAN-1145](https://folio-org.atlassian.net/browse/MODSOURMAN-1145)

MODSOURMAN-1145 Modify action before match breaks non match logs

---

NEWS.md
mod-source-record-manager-server/src/main/java/org/folio/services/migration/impl/AuthorityCancelledLccnMappingRenamingMigration.java
mod-source-record-manager-server/src/main/java/org/folio/services/migration/impl/AuthorityMapping010LccnCustomMigration.java
mod-source-record-manager-server/src/main/java/org/folio/services/migration/impl/BibliographicCancelledLccnMappingRenamingMigration.java
mod-source-record-manager-server/src/main/java/org/folio/services/migration/impl/CancelledLccnMappingRenamingMigration.java
mod-source-record-manager-server/src/main/resources/rules/marc_authority_rules.json
mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json
mod-source-record-manager-server/src/test/java/org/folio/mapping/DefaultRulesMappingTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/migration/impl/AuthorityCancelledLccnMappingRenamingMigrationTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/migration/impl/AuthorityMapping010LccnCustomMigrationTest.java
mod-source-record-manager-server/src/test/java/org/folio/services/migration/impl/BibliographicCancelledLccnMappingRenamingMigrationTest.java
mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json

Change MARC mappings of 010 $z from "Cancelled" LCCN to "Canceled LCCN" 
- change mappings files
- implement migrations for both bib and authority mappings

MODSOURMAN-1188 Change MARC mappings of 010 $z from "Cancelled" LCCN to "Canceled LCCN"

---

mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_job_log_entries_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderRecordProcessingLogCollectionAPITest.java

MODSOURMAN-1200 Remove not updated titles from logs

---

mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

upd test rename it

---

descriptors/ModuleDescriptor-template.json

The main goal is to add additional permissions.

FAT-16548: Additional permissions added.

---

descriptors/ModuleDescriptor-template.json

MODFIN-377 clean up mod-finance permissions

---

descriptors/ModuleDescriptor-template.json

MODSOURMAN-1248 Missing interface dependencies in module descriptor

---

NEWS.md
mod-source-record-manager-server/src/main/resources/templates/db_scripts/create_get_record_processing_log_function.sql
mod-source-record-manager-server/src/test/java/org/folio/rest/impl/metadataProvider/MetaDataProviderJobLogEntriesAPITest.java

[MODSOURMAN-1240](https://folio-org.atlassian.net/browse/MODSOURMAN-1240) The title of record is not displayed on the JSON data after importing file for creating order
upd get_job_processing_log fuction

MODSOURMAN-1240 The title of record is not displayed on the JSON data after importing file for creating order

---

mod-source-record-manager-server/src/main/java/org/folio/verticle/JobExecutionProgressVerticle.java
mod-source-record-manager-server/src/test/java/org/folio/services/RecordProcessedEventHandlingServiceImplTest.java
mod-source-record-manager-server/src/test/java/org/folio/verticle/JobExecutionProgressVerticleTest.java

Data import jobs using Bulk operations data import job profile stuck in progress with 100%
Complete jobExecution when extra processing events received
https://folio-org.atlassian.net/browse/MODSOURMAN-1261

[MODSOURMAN-1261] Complete jobExecution when extra processing events received

---

Dockerfile
README.md
mod-source-record-manager-server/src/main/java/org/folio/verticle/DataImportJournalBatchConsumerVerticle.java

increase session timeouts and heartbeats for consumer

MODSOURMAN-1268 Log entries are empty for completed jobs

---

mod-source-record-manager-server/src/main/resources/rules/marc_bib_rules.json
mod-source-record-manager-server/src/test/resources/org/folio/services/marc_bib_rules.json

MODDICORE-440 Mode of Issuance not being set with MARC to Instance Mapping
* added new rule for LDR

MODDICORE-440 Mode of Issuance not being set with MARC to Instance Mapping

---

.github/workflows/postgres.yml
.rancher-pipeline.yml
Dockerfile
Jenkinsfile
NEWS.md
mod-source-record-manager-server/pom.xml
pom.xml

Migrate to Java 21.
JIRA: https://folio-org.atlassian.net/browse/MODSOURMAN-1283

MODSOURMAN-1283: Java migration to Java 21.

---

mod-source-record-manager-server/src/main/java/org/folio/services/JobExecutionServiceImpl.java
mod-source-record-manager-server/src/main/java/org/folio/verticle/JobExecutionProgressVerticle.java
mod-source-record-manager-server/src/test/java/org/folio/services/JobExecutionProgressServiceImplTest.java

DI_JOB_COMPLETED event is produced more than once
Added pre-checks for the status of the parent jobExecution before setting a new status.
[MODSOURMAN-1287](https://folio-org.atlassian.net/browse/MODSOURMAN-1287)

MODSOURMAN-1287: DI completion event is produced more than once

---

mod-source-record-manager-server/src/main/java/org/folio/services/journal/JournalUtil.java
mod-source-record-manager-server/src/test/java/org/folio/services/JournalUtilTest.java

Fix display of the error message when LINKED_DATA Instance fails to update via DI
Populate journal record for marc during error on Instance without MARC_BIB at context
https://folio-org.atlassian.net/browse/MODSOURMAN-1238

[MODSOURMAN-1238] Populate marc bib journal record if Instance created or updated
